import StaffCard from "../components/StaffCard";
import Timeline from "../components/Timeline";
import { useSchoolSettings } from "../context/SchoolSettingsContext";

const leadership = [
  { image: "/images/director1.jpg", name: "Rev Josephat Andula Okama", position: "Director", description: "Provides strategic leadership and champions academic excellence, character development and the long-term growth of the Centre." },
  { name: "Missionary Martha", position: "Board Member", description: "Supports learner welfare and helps coordinate care and community programmes for children and families." },
  { name: "Missionary Mary", position: "Board Member", description: "Contributes to pastoral care, learner support and the Centre's mission to serve vulnerable children." },
  { name: "Pastor Stephen Olumula", position: "Board Member", description: "Provides leadership on home, school and infrastructure development initiatives." },
];
const staff = [
  { image: "/images/nicholus.png", name: "Mr Nicholus Maleba", position: "Teacher", description: "A committed educator focused on learner progress, discipline and a positive classroom experience." },
  { image: "/images/wilbar.png", name: "Mr Wilberforce Ouma", position: "Teacher", description: "A devoted teacher and talented instrumentalist who brings creativity, mentorship and service to the school community." },
  { image: "/images/gabby.png", name: "Mr Gabriel Odhiambo", position: "Teacher", description: "A consistent and dedicated member of staff committed to supporting learners and the wider school community." },
];

export default function About() {
  const { settings } = useSchoolSettings();
  const { school, about } = settings;
  return <main className="bg-white">
    <section className="relative overflow-hidden bg-gradient-to-br from-blue-950 via-blue-900 to-slate-900 text-white"><div className="absolute inset-0 opacity-20" style={{ backgroundImage: "linear-gradient(135deg, rgba(255,255,255,.12) 1px, transparent 1px)", backgroundSize: "36px 36px" }} /><div className="relative mx-auto max-w-7xl px-5 py-20 sm:px-6 lg:px-8 lg:py-28"><div className="max-w-4xl"><span className="inline-flex rounded-full border border-amber-300/40 bg-amber-300/10 px-4 py-2 text-xs font-black uppercase tracking-[0.18em] text-amber-200">Our story · Our mission · Our people</span><h1 className="mt-6 text-4xl font-black tracking-tight sm:text-5xl lg:text-6xl">{about.title || `About ${school.name}`}</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-blue-100 sm:text-xl">{about.intro}</p><div className="mt-9 flex flex-wrap gap-3"><a href="/register" className="rounded-xl bg-amber-400 px-6 py-3.5 text-sm font-black text-blue-950 shadow-lg hover:bg-amber-300">Join the community</a><a href="/support" className="rounded-xl border border-white/25 bg-white/10 px-6 py-3.5 text-sm font-black text-white">Support our mission</a></div></div></div></section>
    <section className="mx-auto max-w-7xl px-5 py-16 sm:px-6 lg:px-8 lg:py-20"><div className="grid gap-12 lg:grid-cols-[1.1fr_.9fr] lg:items-center"><div><p className="text-xs font-black uppercase tracking-[0.18em] text-amber-600">Who we are</p><h2 className="mt-3 text-3xl font-black tracking-tight text-blue-950 sm:text-4xl">{about.storyTitle}</h2><p className="mt-6 whitespace-pre-line leading-8 text-slate-600">{about.story}</p></div><div className="grid grid-cols-2 gap-4"><div className="rounded-2xl bg-blue-950 p-6 text-white shadow-xl"><p className="text-3xl font-black">2008</p><p className="mt-2 text-sm text-blue-100">Founded with a community-first mission</p></div><div className="rounded-2xl bg-amber-400 p-6 text-blue-950 shadow-xl"><p className="text-3xl font-black">360°</p><p className="mt-2 text-sm font-semibold">Academic, social and spiritual support</p></div><div className="col-span-2 rounded-2xl border border-slate-200 bg-slate-50 p-6"><p className="text-sm font-black uppercase tracking-wider text-slate-500">Our commitment</p><p className="mt-2 text-lg font-bold leading-7 text-blue-950">Every learner deserves to be known, supported, challenged and prepared for a purposeful future.</p></div></div></div></section>
    <section className="bg-slate-50 py-16 sm:py-20"><div className="mx-auto max-w-7xl px-5 sm:px-6 lg:px-8"><div className="mb-10 max-w-2xl"><p className="text-xs font-black uppercase tracking-[0.18em] text-amber-600">What guides us</p><h2 className="mt-3 text-3xl font-black text-blue-950 sm:text-4xl">Mission, vision and values</h2></div><div className="grid gap-5 md:grid-cols-3"><article className="rounded-2xl bg-white p-7 shadow-sm ring-1 ring-slate-200"><div className="text-2xl">🎯</div><h3 className="mt-5 text-xl font-black text-blue-950">Mission</h3><p className="mt-3 leading-7 text-slate-600">{about.mission}</p></article><article className="rounded-2xl bg-blue-950 p-7 text-white shadow-xl"><div className="text-2xl">🌍</div><h3 className="mt-5 text-xl font-black">Vision</h3><p className="mt-3 leading-7 text-blue-100">{about.vision}</p></article><article className="rounded-2xl bg-white p-7 shadow-sm ring-1 ring-slate-200"><div className="text-2xl">⭐</div><h3 className="mt-5 text-xl font-black text-blue-950">Core values</h3><div className="mt-4 flex flex-wrap gap-2">{about.values.map((value) => <span key={value} className="rounded-full bg-blue-50 px-3 py-2 text-sm font-bold text-blue-900">{value}</span>)}</div></article></div></div></section>
    <section className="mx-auto max-w-7xl px-5 py-16 sm:px-6 lg:px-8 lg:py-20"><div className="mb-10 flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[0.18em] text-amber-600">Leadership</p><h2 className="mt-3 text-3xl font-black text-blue-950 sm:text-4xl">School & Orphanage Board</h2></div><p className="max-w-xl text-sm leading-6 text-slate-500">A leadership team committed to responsible stewardship, learner welfare and sustainable growth.</p></div><div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-4">{leadership.map((person) => <StaffCard key={person.name} {...person} />)}</div></section>
    <section className="bg-blue-50 py-16 sm:py-20"><div className="mx-auto max-w-7xl px-5 sm:px-6 lg:px-8"><div className="mb-10"><p className="text-xs font-black uppercase tracking-[0.18em] text-amber-600">Our people</p><h2 className="mt-3 text-3xl font-black text-blue-950 sm:text-4xl">Dedicated school staff</h2></div><div className="grid gap-6 md:grid-cols-3">{staff.map((person) => <StaffCard key={person.name} {...person} />)}</div></div></section>
    <section className="mx-auto max-w-7xl px-5 py-16 sm:px-6 lg:px-8 lg:py-20"><div className="mb-10"><p className="text-xs font-black uppercase tracking-[0.18em] text-amber-600">Milestones</p><h2 className="mt-3 text-3xl font-black text-blue-950 sm:text-4xl">A growing legacy</h2></div><Timeline /></section>
  </main>;
}
