import { Link } from "react-router-dom";
import AdmissionSteps from "../components/AdmissionSteps";
import SchoolCalendar from "../components/SchoolCalendar";
import { useSchoolSettings } from "../context/SchoolSettingsContext";

export default function Academics() {
  const { settings } = useSchoolSettings();
  const { school, academics } = settings;
  return <main className="bg-white"><section className="bg-blue-950 px-5 py-20 text-white md:py-28"><div className="mx-auto max-w-7xl"><p className="text-xs font-black uppercase tracking-[0.25em] text-amber-400">Learning & admissions · {school.name}</p><h1 className="mt-5 max-w-4xl text-4xl font-black leading-tight tracking-tight md:text-6xl">{academics.title}</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-blue-100">{academics.intro}</p><div className="mt-8 flex flex-wrap gap-3"><a href="/documents/admission-form.pdf" download className="rounded-xl bg-amber-400 px-6 py-3.5 font-black text-blue-950 hover:bg-amber-300">Download admission form</a><Link to="/contact" className="rounded-xl border border-blue-700 px-6 py-3.5 font-black text-white">Talk to admissions</Link></div></div></section>
  <section className="mx-auto max-w-7xl px-5 py-20 md:py-24"><div className="max-w-3xl"><p className="text-xs font-black uppercase tracking-[0.22em] text-amber-600">Curriculum</p><h2 className="mt-3 text-3xl font-black text-blue-950 md:text-4xl">{academics.curriculumTitle}</h2><p className="mt-4 leading-7 text-slate-600">{academics.curriculumText}</p></div><div className="mt-10 grid gap-5 md:grid-cols-2">{academics.programmes.map((programme, i) => <article key={`${programme.title}-${i}`} className="rounded-3xl border border-slate-200 bg-white p-7 shadow-sm"><div className="flex items-start justify-between"><div><p className="text-xs font-black uppercase tracking-widest text-amber-600">Programme {String(i + 1).padStart(2, "0")}</p><h3 className="mt-2 text-2xl font-black text-blue-950">{programme.title}</h3></div><span className="rounded-full bg-blue-50 px-3 py-1 text-xs font-bold text-blue-800">{programme.subjects.length} areas</span></div><div className="mt-6 grid grid-cols-1 gap-2 sm:grid-cols-2">{programme.subjects.map((subject) => <div key={subject} className="rounded-xl bg-slate-50 px-4 py-3 text-sm font-semibold text-slate-700">✓ {subject}</div>)}</div></article>)}</div></section>
  <section className="bg-slate-50 px-5 py-20"><div className="mx-auto max-w-7xl"><p className="text-xs font-black uppercase tracking-[0.22em] text-amber-600">Admissions</p><h2 className="mt-3 text-3xl font-black text-blue-950">A clear path into {school.shortName}.</h2><div className="mt-10"><AdmissionSteps /></div></div></section>
  <section className="mx-auto max-w-7xl px-5 py-20"><div className="grid gap-10 lg:grid-cols-[.8fr_1.2fr] lg:items-start"><div><p className="text-xs font-black uppercase tracking-[0.22em] text-amber-600">Fees</p><h2 className="mt-3 text-3xl font-black text-blue-950">Simple, transparent fees.</h2><p className="mt-4 leading-7 text-slate-600">{academics.feeNote}</p></div><div className="overflow-hidden rounded-2xl border border-slate-200 shadow-sm"><table className="w-full text-left text-sm"><thead className="bg-blue-950 text-white"><tr><th className="px-5 py-4">Class</th><th className="px-5 py-4">Term fees</th></tr></thead><tbody><tr className="border-t"><td className="px-5 py-4 font-semibold">Grade 1–3</td><td className="px-5 py-4">KES 2,000</td></tr><tr className="border-t"><td className="px-5 py-4 font-semibold">Grade 4–6</td><td className="px-5 py-4">KES 3,000</td></tr></tbody></table></div></div></section>
  <section className="bg-blue-50 px-5 py-20"><div className="mx-auto max-w-7xl"><SchoolCalendar /></div></section></main>;
}
