import { useState } from "react";
import PortalShell from "../components/PortalShell";
import { apiRequest } from "../services/api";

const audiences = [["all", "Everyone"], ["pupil", "Pupils"], ["parent", "Parents"], ["teacher", "Teachers"], ["sponsor", "Sponsors"]];
export default function AdminCommunications() {
  const [form, setForm] = useState({ title: "", message: "", audience: "all" }); const [status, setStatus] = useState(""); const [error, setError] = useState(""); const [saving, setSaving] = useState(false);
  const submit = async (event) => { event.preventDefault(); if (!form.title.trim() || !form.message.trim()) return setError("Title and message are required."); setSaving(true); setError(""); setStatus(""); try { const result = await apiRequest("/notifications/broadcast", { method: "POST", body: form }); setStatus(`Announcement published to ${result.count || 0} recipient group record(s).`); setForm({ title: "", message: "", audience: "all" }); } catch (e) { setError(e.message || "Unable to publish announcement."); } finally { setSaving(false); } };
  return <PortalShell role="admin"><div className="mx-auto max-w-4xl space-y-6"><header><p className="text-xs font-bold uppercase tracking-[0.2em] text-amber-600">School communications</p><h1 className="mt-2 text-3xl font-black text-blue-950">Announcements Centre</h1><p className="mt-2 text-slate-600">Publish official school updates directly to pupil, parent, teacher and sponsor portals.</p></header>{error && <div className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm font-semibold text-red-700">{error}</div>}{status && <div className="rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-sm font-semibold text-emerald-700">{status}</div>}<form onSubmit={submit} className="rounded-2xl border bg-white p-6 shadow-sm"><div className="grid gap-5"><label className="text-sm font-bold text-slate-700">Audience<select value={form.audience} onChange={(e) => setForm({ ...form, audience: e.target.value })} className="mt-2 w-full rounded-xl border border-slate-200 bg-white px-4 py-3 font-normal outline-none focus:border-blue-500">{audiences.map(([value,label]) => <option key={value} value={value}>{label}</option>)}</select></label><label className="text-sm font-bold text-slate-700">Announcement title<input value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} maxLength={160} className="mt-2 w-full rounded-xl border border-slate-200 px-4 py-3 font-normal outline-none focus:border-blue-500" placeholder="e.g. Mid-term assessment schedule" /></label><label className="text-sm font-bold text-slate-700">Message<textarea value={form.message} onChange={(e) => setForm({ ...form, message: e.target.value })} maxLength={4096} rows={7} className="mt-2 w-full resize-y rounded-xl border border-slate-200 px-4 py-3 font-normal outline-none focus:border-blue-500" placeholder="Write the message to be displayed in the school portal…" /></label><div className="flex items-center justify-between gap-4"><p className="text-xs text-slate-400">Messages are stored in the school notification system.</p><button disabled={saving} className="rounded-xl bg-blue-950 px-6 py-3 text-sm font-black text-white disabled:opacity-50">{saving ? "Publishing…" : "Publish announcement"}</button></div></div></form></div></PortalShell>;
}
