import { useEffect, useState } from "react";
import { settingsApi } from "../services/settingsApi";
import { defaults } from "../context/SchoolSettingsContext";

const clone = (value) => JSON.parse(JSON.stringify(value));

function Field({ label, value, onChange, multiline = false, type = "text", hint }) {
  const className = "mt-2 w-full rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm text-slate-900 outline-none transition focus:border-blue-500 focus:ring-2 focus:ring-blue-100";
  return <label className="block"><span className="text-sm font-bold text-slate-700">{label}</span>{hint && <span className="ml-2 text-xs text-slate-400">{hint}</span>}{multiline ? <textarea rows={4} value={value ?? ""} onChange={(e) => onChange(e.target.value)} className={className} /> : <input type={type} value={value ?? ""} onChange={(e) => onChange(e.target.value)} className={className} />}</label>;
}

function Section({ title, description, children }) {
  return <section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="text-xl font-black text-blue-950">{title}</h2>{description && <p className="mt-1 text-sm text-slate-500">{description}</p>}<div className="mt-6 grid gap-5">{children}</div></section>;
}

export default function AdminSettings() {
  const [settings, setSettings] = useState(clone(defaults));
  const [tab, setTab] = useState("school");
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [message, setMessage] = useState("");
  const [error, setError] = useState("");

  useEffect(() => {
    settingsApi.get().then((payload) => setSettings(payload?.data || clone(defaults))).catch((err) => setError(err.message)).finally(() => setLoading(false));
  }, []);

  const update = (section, key, value) => setSettings((current) => ({ ...current, [section]: { ...current[section], [key]: value } }));
  const updateArrayItem = (section, key, index, field, value) => setSettings((current) => { const items = [...(current[section]?.[key] || [])]; items[index] = { ...items[index], [field]: value }; return { ...current, [section]: { ...current[section], [key]: items } }; });
  const updateValueArray = (section, key, index, value) => setSettings((current) => { const items = [...(current[section]?.[key] || [])]; items[index] = value; return { ...current, [section]: { ...current[section], [key]: items } }; });

  async function save() {
    setSaving(true); setMessage(""); setError("");
    try { const payload = await settingsApi.update(settings); setSettings(payload?.data || settings); setMessage("Settings saved. The public website will use the new content immediately."); }
    catch (err) { setError(err.message); }
    finally { setSaving(false); }
  }

  const tabs = [["school", "School & contact"], ["home", "Homepage"], ["about", "About"], ["academics", "Academics"], ["support", "Support"]];
  if (loading) return <div className="rounded-2xl bg-white p-8 shadow-sm">Loading school settings…</div>;

  return <div className="mx-auto max-w-6xl space-y-6">
    <div className="rounded-2xl bg-gradient-to-r from-blue-950 to-blue-900 p-7 text-white shadow-lg"><p className="text-xs font-black uppercase tracking-[0.2em] text-amber-300">Central website control</p><h1 className="mt-2 text-3xl font-black">School Settings</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-blue-100">Change the school's identity, contact details and public website content from one place. Saved changes are delivered through the shared settings service across the site.</p></div>
    <div className="flex flex-wrap gap-2 rounded-2xl border border-slate-200 bg-slate-50 p-2">{tabs.map(([id, label]) => <button key={id} onClick={() => setTab(id)} className={`rounded-xl px-4 py-2.5 text-sm font-bold transition ${tab === id ? "bg-blue-950 text-white shadow" : "text-slate-600 hover:bg-white"}`}>{label}</button>)}</div>
    {message && <div className="rounded-xl border border-green-200 bg-green-50 px-4 py-3 text-sm font-bold text-green-700">{message}</div>}
    {error && <div className="rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm font-bold text-red-700">{error}</div>}

    {tab === "school" && <div className="grid gap-6 lg:grid-cols-2">
      <Section title="School identity" description="These values are shared by navigation, footer, public pages and portal-facing branding."><Field label="School name" value={settings.school.name} onChange={(v) => update("school", "name", v)} /><Field label="Short name" value={settings.school.shortName} onChange={(v) => update("school", "shortName", v)} /><Field label="Motto / tagline" value={settings.school.motto} onChange={(v) => update("school", "motto", v)} /><Field label="School description" value={settings.school.description} onChange={(v) => update("school", "description", v)} multiline /><Field label="Logo URL" value={settings.school.logo} onChange={(v) => update("school", "logo", v)} hint="Use a hosted/public image URL" /></Section>
      <Section title="Contact information" description="The contact page, footer and school communications can use these values."><Field label="Phone" value={settings.contact.phone} onChange={(v) => update("contact", "phone", v)} /><Field label="Email" value={settings.contact.email} onChange={(v) => update("contact", "email", v)} type="email" /><Field label="WhatsApp" value={settings.contact.whatsapp} onChange={(v) => update("contact", "whatsapp", v)} /><Field label="Physical address" value={settings.contact.address} onChange={(v) => update("contact", "address", v)} /><Field label="Postal address" value={settings.contact.postalAddress} onChange={(v) => update("contact", "postalAddress", v)} /><Field label="Office hours" value={settings.contact.officeHours} onChange={(v) => update("contact", "officeHours", v)} /><Field label="Map embed URL" value={settings.contact.mapEmbed} onChange={(v) => update("contact", "mapEmbed", v)} /></Section>
      <Section title="Social links"><div className="grid gap-5 sm:grid-cols-2"><Field label="Facebook" value={settings.social.facebook} onChange={(v) => update("social", "facebook", v)} /><Field label="YouTube" value={settings.social.youtube} onChange={(v) => update("social", "youtube", v)} /><Field label="X / Twitter" value={settings.social.twitter} onChange={(v) => update("social", "twitter", v)} /><Field label="Instagram" value={settings.social.instagram} onChange={(v) => update("social", "instagram", v)} /></div></Section>
      <Section title="Footer"><Field label="Footer description" value={settings.footer.description} onChange={(v) => update("footer", "description", v)} multiline /></Section>
    </div>}

    {tab === "home" && <div className="space-y-6">
      <Section title="Hero"><Field label="Eyebrow" value={settings.homepage.eyebrow} onChange={(v) => update("homepage", "eyebrow", v)} /><Field label="Hero title" value={settings.homepage.heroTitle} onChange={(v) => update("homepage", "heroTitle", v)} multiline /><Field label="Hero description" value={settings.homepage.heroText} onChange={(v) => update("homepage", "heroText", v)} multiline /><Field label="Hero image URL" value={settings.homepage.heroImage} onChange={(v) => update("homepage", "heroImage", v)} /></Section>
      <Section title="Impact statistics"><div className="grid gap-5 md:grid-cols-2">{settings.homepage.stats.map((item, i) => <div key={i} className="rounded-xl bg-slate-50 p-4"><Field label={`Statistic ${i + 1} value`} value={item.value} onChange={(v) => updateArrayItem("homepage", "stats", i, "value", v)} /><div className="mt-4"><Field label="Label" value={item.label} onChange={(v) => updateArrayItem("homepage", "stats", i, "label", v)} /></div></div>)}</div></Section>
      <Section title="Education section"><Field label="Eyebrow" value={settings.homepage.educationEyebrow} onChange={(v) => update("homepage", "educationEyebrow", v)} /><Field label="Title" value={settings.homepage.educationTitle} onChange={(v) => update("homepage", "educationTitle", v)} multiline /><Field label="Text" value={settings.homepage.educationText} onChange={(v) => update("homepage", "educationText", v)} multiline /></Section>
      <Section title="School promises"><div className="grid gap-5 lg:grid-cols-3">{settings.homepage.pillars.map((item, i) => <div key={i} className="rounded-xl bg-slate-50 p-4"><Field label="Number" value={item.number} onChange={(v) => updateArrayItem("homepage", "pillars", i, "number", v)} /><div className="mt-4"><Field label="Title" value={item.title} onChange={(v) => updateArrayItem("homepage", "pillars", i, "title", v)} /></div><div className="mt-4"><Field label="Description" value={item.text} onChange={(v) => updateArrayItem("homepage", "pillars", i, "text", v)} multiline /></div></div>)}</div></Section>
      <Section title="Community section"><Field label="Eyebrow" value={settings.homepage.communityEyebrow} onChange={(v) => update("homepage", "communityEyebrow", v)} /><Field label="Title" value={settings.homepage.communityTitle} onChange={(v) => update("homepage", "communityTitle", v)} /><Field label="Description" value={settings.homepage.communityText} onChange={(v) => update("homepage", "communityText", v)} multiline /><div className="grid gap-5 lg:grid-cols-3">{settings.homepage.pathways.map((item, i) => <div key={i} className="rounded-xl bg-slate-50 p-4"><Field label="Eyebrow" value={item.eyebrow} onChange={(v) => updateArrayItem("homepage", "pathways", i, "eyebrow", v)} /><div className="mt-4"><Field label="Title" value={item.title} onChange={(v) => updateArrayItem("homepage", "pathways", i, "title", v)} /></div><div className="mt-4"><Field label="Text" value={item.text} onChange={(v) => updateArrayItem("homepage", "pathways", i, "text", v)} multiline /></div><div className="mt-4"><Field label="Link" value={item.href} onChange={(v) => updateArrayItem("homepage", "pathways", i, "href", v)} /></div><div className="mt-4"><Field label="Action" value={item.action} onChange={(v) => updateArrayItem("homepage", "pathways", i, "action", v)} /></div></div>)}</div></Section>
      <Section title="Development fund & final call to action"><Field label="Fund eyebrow" value={settings.homepage.developmentEyebrow} onChange={(v) => update("homepage", "developmentEyebrow", v)} /><Field label="Fund title" value={settings.homepage.developmentTitle} onChange={(v) => update("homepage", "developmentTitle", v)} /><Field label="Fund description" value={settings.homepage.developmentText} onChange={(v) => update("homepage", "developmentText", v)} multiline /><Field label="Fund goal" value={settings.homepage.developmentGoal} onChange={(v) => update("homepage", "developmentGoal", v)} /><Field label="Final CTA eyebrow" value={settings.homepage.finalEyebrow} onChange={(v) => update("homepage", "finalEyebrow", v)} /><Field label="Final CTA title" value={settings.homepage.finalTitle} onChange={(v) => update("homepage", "finalTitle", v)} /></Section>
    </div>}

    {tab === "about" && <Section title="About page content"><Field label="Page title" value={settings.about.title} onChange={(v) => update("about", "title", v)} /><Field label="Introduction" value={settings.about.intro} onChange={(v) => update("about", "intro", v)} multiline /><Field label="Story section title" value={settings.about.storyTitle} onChange={(v) => update("about", "storyTitle", v)} /><Field label="School story" value={settings.about.story} onChange={(v) => update("about", "story", v)} multiline /><Field label="Mission" value={settings.about.mission} onChange={(v) => update("about", "mission", v)} multiline /><Field label="Vision" value={settings.about.vision} onChange={(v) => update("about", "vision", v)} multiline /><Field label="Core values" value={settings.about.values.join(", ")} onChange={(v) => update("about", "values", v.split(",").map((x) => x.trim()).filter(Boolean))} hint="Separate values with commas" /></Section>}

    {tab === "academics" && <div className="space-y-6"><Section title="Academics page"><Field label="Hero title" value={settings.academics.title} onChange={(v) => update("academics", "title", v)} multiline /><Field label="Introduction" value={settings.academics.intro} onChange={(v) => update("academics", "intro", v)} multiline /><Field label="Curriculum title" value={settings.academics.curriculumTitle} onChange={(v) => update("academics", "curriculumTitle", v)} /><Field label="Curriculum description" value={settings.academics.curriculumText} onChange={(v) => update("academics", "curriculumText", v)} multiline /><Field label="Fee note" value={settings.academics.feeNote} onChange={(v) => update("academics", "feeNote", v)} multiline /></Section><Section title="Programmes & subjects"><div className="grid gap-5 md:grid-cols-2">{settings.academics.programmes.map((item, i) => <div key={i} className="rounded-xl bg-slate-50 p-4"><Field label="Programme title" value={item.title} onChange={(v) => updateArrayItem("academics", "programmes", i, "title", v)} /><div className="mt-4"><Field label="Subjects" value={item.subjects.join(", ")} onChange={(v) => updateArrayItem("academics", "programmes", i, "subjects", v.split(",").map((x) => x.trim()).filter(Boolean))} multiline hint="Separate subjects with commas" /></div></div>)}</div></Section></div>}

    {tab === "support" && <div className="space-y-6"><Section title="Support page"><Field label="Hero title" value={settings.support.title} onChange={(v) => update("support", "title", v)} multiline /><Field label="Introduction" value={settings.support.intro} onChange={(v) => update("support", "intro", v)} multiline /><Field label="Priority section title" value={settings.support.priorityTitle} onChange={(v) => update("support", "priorityTitle", v)} /><Field label="Donation instructions" value={settings.support.donationText} onChange={(v) => update("support", "donationText", v)} multiline /></Section><Section title="Support priorities"><div className="grid gap-5 lg:grid-cols-3">{settings.support.priorities.map((item, i) => <div key={i} className="rounded-xl bg-slate-50 p-4"><Field label="Title" value={item.title} onChange={(v) => updateArrayItem("support", "priorities", i, "title", v)} /><div className="mt-4"><Field label="Description" value={item.description} onChange={(v) => updateArrayItem("support", "priorities", i, "description", v)} multiline /></div><div className="mt-4"><Field label="Target" value={item.amount} onChange={(v) => updateArrayItem("support", "priorities", i, "amount", v)} /></div><div className="mt-4"><Field label="Icon" value={item.icon} onChange={(v) => updateArrayItem("support", "priorities", i, "icon", v)} /></div></div>)}</div></Section></div>}

    <div className="sticky bottom-4 flex justify-end"><button onClick={save} disabled={saving} className="rounded-xl bg-amber-400 px-7 py-3.5 font-black text-blue-950 shadow-xl transition hover:bg-amber-300 disabled:cursor-not-allowed disabled:opacity-60">{saving ? "Saving changes…" : "Save all settings"}</button></div>
  </div>;
}
