import { useState } from "react";
import { Link, useNavigate, useSearchParams } from "react-router-dom";
import { authApi } from "../services/api";

export function Login() { const navigate = useNavigate(); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [error, setError] = useState(""); const submit = async (e) => { e.preventDefault(); setError(""); try { const result = await authApi.login({ email, password }); localStorage.setItem("angelshome_token", result.token); localStorage.setItem("angelshome_session", JSON.stringify(result.user)); navigate(`/portal/${result.user.role}`); } catch (err) { setError(err.message); } }; return <AuthLayout title="Welcome back" subtitle="Sign in to your secure Angels Home portal."><form onSubmit={submit} className="space-y-4">{error && <p className="rounded-xl bg-red-50 p-3 text-sm font-semibold text-red-700">{error}</p>}<Field label="Email" type="email" value={email} onChange={setEmail} required /><Field label="Password" type="password" value={password} onChange={setPassword} required /><button className="w-full rounded-xl bg-blue-950 px-5 py-3.5 font-black text-white hover:bg-blue-900">Sign in</button><p className="text-center text-sm text-slate-600">New to the portal? <Link className="font-bold text-blue-700" to="/register">Create an account</Link></p></form></AuthLayout>; }

export function Register() { const navigate = useNavigate(); const [params] = useSearchParams(); const [form, setForm] = useState({ name: "", email: "", password: "", role: params.get("role") || "pupil" }); const [error, setError] = useState(""); const submit = async (e) => { e.preventDefault(); setError(""); try { const result = await authApi.register(form); localStorage.setItem("angelshome_token", result.token); localStorage.setItem("angelshome_session", JSON.stringify(result.user)); navigate(`/portal/${result.user.role}`); } catch (err) { setError(err.message); } }; return <AuthLayout title="Create your portal account" subtitle="Choose your role and start using the Angels Home digital platform."><form onSubmit={submit} className="space-y-4">{error && <p className="rounded-xl bg-red-50 p-3 text-sm font-semibold text-red-700">{error}</p>}<Field label="Full name" value={form.name} onChange={(v) => setForm({ ...form, name: v })} required /><Field label="Email" type="email" value={form.email} onChange={(v) => setForm({ ...form, email: v })} required /><div><label className="mb-2 block text-sm font-bold text-slate-700">Portal role</label><select value={form.role} onChange={(e) => setForm({ ...form, role: e.target.value })} className="w-full rounded-xl border border-slate-300 px-4 py-3"><option value="pupil">Pupil</option><option value="parent">Parent</option><option value="teacher">Teacher</option><option value="sponsor">Sponsor</option></select></div><Field label="Password" type="password" value={form.password} onChange={(v) => setForm({ ...form, password: v })} required /><button className="w-full rounded-xl bg-blue-950 px-5 py-3.5 font-black text-white">Create account</button><p className="text-center text-sm text-slate-600">Already registered? <Link className="font-bold text-blue-700" to="/login">Sign in</Link></p></form></AuthLayout>; }
function Field({ label, type = "text", value, onChange, required }) { return <div><label className="mb-2 block text-sm font-bold text-slate-700">{label}</label><input required={required} type={type} value={value} onChange={(e) => onChange(e.target.value)} className="w-full rounded-xl border border-slate-300 px-4 py-3 outline-none focus:border-blue-700 focus:ring-2 focus:ring-blue-100" /></div>; }
function AuthLayout({ title, subtitle, children }) { return <div className="flex min-h-screen items-center justify-center bg-gradient-to-br from-blue-950 via-blue-900 to-slate-900 px-4 py-10"><div className="w-full max-w-md rounded-3xl bg-white p-7 shadow-2xl md:p-9"><Link to="/" className="text-sm font-black text-amber-600">← Angels Home Education Centre</Link><h1 className="mt-7 text-3xl font-black text-blue-950">{title}</h1><p className="mt-2 mb-7 text-sm leading-6 text-slate-500">{subtitle}</p>{children}</div></div>; }
