import { Link } from "react-router-dom";

const cards = {
  teachers: [["Grace Njeri", "Head of Mathematics", "/images/gabby.png"], ["Peter Kamau", "English & Literature", "/images/mwalimu.jpg"], ["Mary Achieng", "Science & Technology", "/images/nicholus.png"]],
  pupils: [["Learner success", "Structured learning, mentorship and pastoral care."], ["Clubs & talent", "Safe spaces for creativity, sport and leadership."], ["Digital learning", "Technology-enabled learning resources for every class."]],
  sponsors: [["Education partners", "Support scholarships, learning resources and school development."], ["Community partners", "Help us expand access to safe, quality education."], ["Individual sponsors", "Sponsor a learner or contribute to a school project."]],
};

export default function Community({ type }) { const title = type === "teachers" ? "Our Teachers" : type === "pupils" ? "Our Pupils" : "Our Sponsors & Partners"; return <div className="bg-white"><section className="bg-blue-950 px-5 py-20 text-white"><div className="mx-auto max-w-7xl"><p className="text-sm font-bold uppercase tracking-[0.2em] text-amber-400">Angels Home community</p><h1 className="mt-4 max-w-3xl text-4xl font-black md:text-6xl">{title}</h1><p className="mt-5 max-w-2xl text-lg leading-8 text-blue-100">People and partners working together to create a stronger future for every child.</p></div></section><section className="mx-auto max-w-7xl px-5 py-16"><div className="grid gap-6 md:grid-cols-3">{cards[type].map((card) => <article key={card[0]} className="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm transition hover:-translate-y-1 hover:shadow-xl">{type === "teachers" && <img src={card[2]} alt={card[0]} className="h-64 w-full object-cover" />}<div className="p-7"><p className="text-xs font-bold uppercase tracking-widest text-amber-600">{type === "teachers" ? "Educator" : "Community"}</p><h2 className="mt-2 text-2xl font-black text-blue-950">{card[0]}</h2><p className="mt-3 leading-7 text-slate-600">{card[1]}</p></div></article>)}</div><div className="mt-12 rounded-3xl bg-slate-50 p-8 text-center"><h2 className="text-2xl font-black text-blue-950">Be part of the journey</h2><p className="mx-auto mt-3 max-w-xl text-slate-600">Create a portal account to access school services, updates and secure communication.</p><Link to="/register" className="mt-6 inline-flex rounded-xl bg-blue-950 px-6 py-3 font-black text-white">Create portal account</Link></div></section></div>; }
