import { Link } from "react-router-dom";

const content = {
  teachers: { eyebrow: "Our educators", title: "Experienced people. Purposeful teaching.", text: "Our teachers bring knowledge, care and consistency to the classroom while helping learners discover their strengths.", cards: [["Grace Njeri", "Head of Mathematics", "/images/gabby.png"], ["Peter Kamau", "English & Literature", "/images/mwalimu.jpg"], ["Mary Achieng", "Science & Technology", "/images/nicholus.png"]] },
  pupils: { eyebrow: "Our learners", title: "Every learner seen. Every potential encouraged.", text: "We create a safe, structured environment where pupils can learn, participate, build confidence and develop leadership skills.", cards: [["Learning & progress", "Structured teaching, mentorship and pastoral support help learners build strong foundations."], ["Clubs & talent", "Sport, music, debate and creative activities provide space to discover and develop talent."], ["Digital learning", "Technology and practical skills prepare learners for further education and the world beyond school."]] },
  sponsors: { eyebrow: "Partners & supporters", title: "Investing in education. Creating lasting impact.", text: "Our supporters help make quality education, learner welfare and school development possible.", cards: [["Education partners", "Support scholarships, learning resources and programmes that directly strengthen learner outcomes."], ["Community partners", "Work with the Centre on initiatives that expand access to safe, quality education."], ["Individual sponsors", "Sponsor a learner or contribute to a clearly defined school development priority."]] },
};

export default function Community({ type }) { const page = content[type]; const isTeachers = type === "teachers"; return <main className="bg-white"><section className="bg-blue-950 px-5 py-20 text-white md:py-28"><div className="mx-auto max-w-7xl"><p className="text-xs font-black uppercase tracking-[0.25em] text-amber-400">Angels Home community · {page.eyebrow}</p><h1 className="mt-5 max-w-4xl text-4xl font-black leading-tight tracking-tight md:text-6xl">{page.title}</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-blue-100">{page.text}</p></div></section><section className="mx-auto max-w-7xl px-5 py-20 md:py-24"><div className={`grid gap-6 ${isTeachers ? "md:grid-cols-3" : "md:grid-cols-3"}`}>{page.cards.map((card) => <article key={card[0]} className="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm transition hover:-translate-y-1 hover:shadow-xl">{isTeachers && <img src={card[2]} alt={card[0]} className="h-72 w-full object-cover" loading="lazy" onError={(e) => { e.currentTarget.style.display = "none"; }} />}<div className="p-7"><p className="text-xs font-black uppercase tracking-widest text-amber-600">{isTeachers ? "Educator" : type === "pupils" ? "Learner experience" : "Partnership"}</p><h2 className="mt-3 text-2xl font-black text-blue-950">{card[0]}</h2><p className="mt-3 leading-7 text-slate-600">{card[1]}</p></div></article>)}</div><div className="mt-14 rounded-[2rem] bg-slate-50 p-8 md:p-10"><div className="grid gap-8 md:grid-cols-[1fr_auto] md:items-center"><div><p className="text-xs font-black uppercase tracking-widest text-amber-600">Next step</p><h2 className="mt-2 text-2xl font-black text-blue-950">Be part of the Angels Home journey.</h2><p className="mt-3 max-w-2xl leading-7 text-slate-600">Connect with the Centre, access secure school services or explore ways to support our learners.</p></div><div className="flex flex-wrap gap-3"><Link to="/register" className="rounded-xl bg-blue-950 px-5 py-3 font-black text-white">Create portal account</Link><Link to="/contact" className="rounded-xl border border-slate-300 px-5 py-3 font-black text-slate-700">Contact the Centre</Link></div></div></div></section></main>; }
