import ContactForm from "../components/ContactForm";
import SocialLinks from "../components/SocialLinks";
import { useSchoolSettings } from "../context/SchoolSettingsContext";

export default function Contact() {
  const { settings } = useSchoolSettings();
  const { school, contact } = settings;
  const contactCards = [["Visit the Centre", contact.address, contact.postalAddress], ["Call the school", contact.phone, "For admissions, learner welfare and general enquiries."], ["Email the office", contact.email, contact.officeHours]];
  return <main className="bg-white"><section className="bg-blue-950 px-5 py-20 text-white md:py-28"><div className="mx-auto max-w-7xl"><p className="text-xs font-black uppercase tracking-[0.25em] text-amber-400">Contact & admissions</p><h1 className="mt-5 max-w-4xl text-4xl font-black leading-tight tracking-tight md:text-6xl">Let's start a conversation about your child's future.</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-blue-100">Speak with the {school.name} team about admissions, learning, partnerships, support or general school enquiries.</p></div></section>
<section className="mx-auto max-w-7xl px-5 py-20 md:py-24"><div className="grid gap-12 lg:grid-cols-[.85fr_1.15fr] lg:items-start"><div><p className="text-xs font-black uppercase tracking-[0.22em] text-amber-600">School office</p><h2 className="mt-3 text-3xl font-black text-blue-950">How can we help?</h2><p className="mt-4 leading-7 text-slate-600">Our office is available to assist families, prospective learners, educators and partners.</p><div className="mt-8 space-y-4">{contactCards.map(([title, value, detail]) => <div key={title} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-xs font-black uppercase tracking-widest text-amber-600">{title}</p><p className="mt-2 font-black text-blue-950">{value}</p><p className="mt-1 text-sm leading-6 text-slate-600">{detail}</p></div>)}</div><div className="mt-7"><SocialLinks /></div></div><div className="rounded-3xl border border-slate-200 bg-slate-50 p-6 shadow-sm md:p-8"><p className="text-xs font-black uppercase tracking-widest text-amber-600">Send an enquiry</p><h2 className="mt-2 text-2xl font-black text-blue-950">Contact the school</h2><p className="mb-6 mt-2 text-sm leading-6 text-slate-600">Please provide enough detail for our team to route your enquiry to the right person.</p><ContactForm /></div></div></section>
<section className="bg-slate-50 px-5 py-16"><div className="mx-auto max-w-7xl"><div className="mb-7"><p className="text-xs font-black uppercase tracking-widest text-amber-600">Find us</p><h2 className="mt-2 text-3xl font-black text-blue-950">Our location</h2></div><div className="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm"><iframe title={`${school.name} location`} className="h-[320px] w-full border-0 sm:h-[430px]" src={contact.mapEmbed} loading="lazy" allowFullScreen referrerPolicy="no-referrer-when-downgrade" /></div></div></section></main>;
}
