import { Link } from "react-router-dom";
import HeroSlider from "../components/HeroSlider";
import ProgressBar from "../components/ProgressBar";
import LatestNews from "../components/LatestNews";

const pillars = [
  ["01", "Academic excellence", "Strong foundations, purposeful teaching and measurable learner progress."],
  ["02", "Character & faith", "Discipline, integrity, compassion and leadership are woven into school life."],
  ["03", "Whole-child care", "Pastoral support, creativity, sport and mentorship help every learner flourish."],
];

export default function Home() {
  return <main className="bg-white">
    <HeroSlider />
    <section className="mx-auto max-w-7xl px-5 py-20 md:py-28"><div className="grid gap-12 lg:grid-cols-[1.08fr_.92fr] lg:items-center"><div><p className="text-xs font-black uppercase tracking-[0.25em] text-amber-600">Welcome to Angels Home Education Centre</p><h1 className="mt-5 max-w-4xl text-4xl font-black leading-[1.05] tracking-tight text-blue-950 sm:text-5xl md:text-6xl">Education that shapes character, purpose and opportunity.</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-600">We provide affordable, quality and holistic education in a caring environment where learners are challenged to excel and equipped to serve their communities.</p><div className="mt-8 flex flex-wrap gap-3"><Link to="/academics" className="rounded-xl bg-blue-950 px-6 py-3.5 font-black text-white shadow-lg shadow-blue-950/10 hover:bg-blue-900">Explore academics</Link><Link to="/support" className="rounded-xl border border-slate-300 px-6 py-3.5 font-black text-slate-700 hover:border-blue-300">Support the Centre</Link></div></div><div className="rounded-[2rem] border border-slate-200 bg-slate-50 p-7 shadow-sm"><p className="text-xs font-black uppercase tracking-[0.2em] text-amber-600">Our promise</p><div className="mt-6 space-y-6">{pillars.map(([n,t,d]) => <div key={n} className="flex gap-4"><span className="mt-1 flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-amber-100 text-xs font-black text-amber-700">{n}</span><div><h3 className="font-black text-blue-950">{t}</h3><p className="mt-1 text-sm leading-6 text-slate-600">{d}</p></div></div>)}</div></div></div></section>
    <section className="bg-blue-950 px-5 py-16 text-white"><div className="mx-auto max-w-7xl"><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[["248+", "Learners served"], ["24", "Dedicated teachers"], ["94%", "Average attendance"], ["10+", "Years of impact"]].map(([v,l]) => <div key={l} className="border-l-2 border-amber-400/80 px-6 py-3"><p className="text-3xl font-black text-amber-400">{v}</p><p className="mt-2 text-sm font-semibold text-blue-100">{l}</p></div>)}</div></div></section>
    <section className="mx-auto max-w-7xl px-5 py-20 md:py-24"><div className="max-w-3xl"><p className="text-xs font-black uppercase tracking-[0.22em] text-amber-600">A community built around learners</p><h2 className="mt-3 text-3xl font-black tracking-tight text-blue-950 md:text-4xl">One school. One community. One future.</h2><p className="mt-4 leading-7 text-slate-600">Whether you are a parent, teacher, sponsor or community partner, there is a meaningful way to participate in the Angels Home journey.</p></div><div className="mt-10 grid gap-5 md:grid-cols-3">{[["Parents & pupils", "Access learning support, school information and secure portal services.", "/register?role=parent"], ["Teachers", "Connect with colleagues, manage learning and communicate with families.", "/register?role=teacher"], ["Sponsors & partners", "Follow your contribution and help fund meaningful education programmes.", "/register?role=sponsor"]].map(([t,d,h]) => <Link key={t} to={h} className="group rounded-3xl border border-slate-200 bg-white p-7 shadow-sm transition hover:-translate-y-1 hover:border-blue-200 hover:shadow-xl"><p className="text-xs font-black uppercase tracking-widest text-amber-600">Community</p><h3 className="mt-3 text-xl font-black text-blue-950">{t}</h3><p className="mt-3 leading-7 text-slate-600">{d}</p><span className="mt-6 inline-block text-sm font-black text-blue-700 group-hover:text-amber-600">Get started →</span></Link>)}</div></section>
    <LatestNews />
    <section className="mx-auto max-w-7xl px-5 py-20"><ProgressBar /></section>
  </main>;
}
