import { Link } from "react-router-dom";
import HeroSlider from "../components/HeroSlider";
import ProgressBar from "../components/ProgressBar";
import LatestNews from "../components/LatestNews";

export default function Home() {
  return <div className="bg-white">
    <HeroSlider />
    <section className="mx-auto max-w-7xl px-5 py-16 md:py-24"><div className="grid gap-12 lg:grid-cols-[1.1fr_.9fr] lg:items-center"><div><p className="text-sm font-black uppercase tracking-[0.2em] text-amber-600">Education with purpose</p><h1 className="mt-4 text-4xl font-black leading-tight text-blue-950 md:text-6xl">Every child deserves the chance to thrive.</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-600">Angels Home Education Centre nurtures academic excellence, discipline, character and confidence in a caring environment.</p><div className="mt-8 flex flex-wrap gap-3"><Link to="/register" className="rounded-xl bg-blue-950 px-6 py-3.5 font-black text-white shadow-lg shadow-blue-950/10">Access school portal</Link><Link to="/support" className="rounded-xl border border-slate-300 px-6 py-3.5 font-black text-slate-700">Support our mission</Link></div></div><div className="rounded-3xl bg-slate-50 p-7 ring-1 ring-slate-100"><p className="text-xs font-black uppercase tracking-widest text-amber-600">Our commitment</p><div className="mt-5 space-y-5">{[["01", "Academic excellence", "Strong foundations and meaningful learning."], ["02", "Character & discipline", "Values that prepare learners for life."], ["03", "Whole-child support", "Pastoral care, creativity and leadership."]].map(([n,t,d]) => <div key={n} className="flex gap-4"><span className="text-sm font-black text-amber-500">{n}</span><div><h3 className="font-black text-blue-950">{t}</h3><p className="mt-1 text-sm leading-6 text-slate-600">{d}</p></div></div>)}</div></div></div></section>
    <section className="bg-blue-950 px-5 py-16 text-white"><div className="mx-auto max-w-7xl"><div className="grid gap-5 md:grid-cols-4">{[["248+", "Learners"], ["24", "Dedicated teachers"], ["94%", "Average attendance"], ["10+", "Years of impact"]].map(([v,l]) => <div key={l} className="rounded-2xl border border-blue-800 bg-blue-900/40 p-6"><p className="text-3xl font-black text-amber-400">{v}</p><p className="mt-2 text-sm font-semibold text-blue-100">{l}</p></div>)}</div></div></section>
    <section className="mx-auto max-w-7xl px-5 py-16 md:py-20"><div className="mb-10 flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-black uppercase tracking-widest text-amber-600">Get involved</p><h2 className="mt-2 text-3xl font-black text-blue-950">One school. One community. One future.</h2></div></div><div className="grid gap-5 md:grid-cols-3">{[["For Parents & Pupils", "Access reports, school updates and learning support.", "/register?role=parent"], ["For Teachers", "Manage classes, attendance and school communication.", "/register?role=teacher"], ["For Sponsors", "Follow your impact and support meaningful programmes.", "/register?role=sponsor"]].map(([t,d,h]) => <Link key={t} to={h} className="group rounded-3xl border border-slate-200 p-7 transition hover:-translate-y-1 hover:border-blue-200 hover:shadow-xl"><h3 className="text-xl font-black text-blue-950">{t}</h3><p className="mt-3 leading-7 text-slate-600">{d}</p><span className="mt-6 inline-block text-sm font-black text-blue-700 group-hover:text-amber-600">Get started →</span></Link>)}</div></section>
    <LatestNews /><section className="mx-auto max-w-7xl px-5 py-16"><ProgressBar /></section>
  </div>;
}
