import { Link } from "react-router-dom";
import LatestNews from "../components/LatestNews";
import { useSchoolSettings } from "../context/SchoolSettingsContext";

export default function Home() {
  const { settings } = useSchoolSettings();
  const { school, homepage } = settings;
  return <main className="bg-white text-slate-900">
    <section className="relative isolate min-h-[620px] overflow-hidden bg-blue-950 text-white lg:min-h-[680px]"><img src={homepage.heroImage} alt={school.name} className="absolute inset-0 -z-20 h-full w-full object-cover" /><div className="absolute inset-0 -z-10 bg-gradient-to-r from-blue-950 via-blue-950/85 to-blue-950/35" /><div className="absolute inset-x-0 bottom-0 -z-10 h-40 bg-gradient-to-t from-blue-950/70 to-transparent" /><div className="mx-auto flex min-h-[620px] max-w-7xl items-center px-5 py-24 lg:min-h-[680px] lg:px-8"><div className="max-w-3xl"><div className="inline-flex items-center gap-2 rounded-full border border-white/20 bg-white/10 px-4 py-2 text-xs font-black uppercase tracking-[0.18em] text-amber-200 backdrop-blur"><span className="h-2 w-2 rounded-full bg-amber-300" />{homepage.eyebrow}</div><h1 className="mt-6 text-5xl font-black leading-[1.05] tracking-tight sm:text-6xl lg:text-7xl">{homepage.heroTitle}</h1><p className="mt-7 max-w-2xl text-lg leading-8 text-blue-50 sm:text-xl">{homepage.heroText}</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><Link to="/register?role=parent" className="rounded-xl bg-amber-400 px-6 py-3.5 text-center font-black text-blue-950 shadow-xl transition hover:-translate-y-0.5 hover:bg-amber-300">Enquire about admissions</Link><Link to="/support" className="rounded-xl border border-white/30 bg-white/10 px-6 py-3.5 text-center font-black text-white backdrop-blur transition hover:bg-white/20">Support our mission</Link></div><div className="mt-10 flex flex-wrap gap-x-7 gap-y-3 text-sm font-semibold text-blue-100"><span>✓ Caring learning environment</span><span>✓ Purposeful teaching</span><span>✓ Character-led development</span></div></div></div></section>
    <section className="relative z-10 -mt-10 mx-auto max-w-7xl px-5 lg:px-8"><div className="grid overflow-hidden rounded-2xl bg-white shadow-2xl ring-1 ring-slate-200 sm:grid-cols-2 lg:grid-cols-4">{homepage.stats.map((stat, i) => <div key={`${stat.label}-${i}`} className="border-b border-slate-100 px-6 py-7 text-center sm:border-r lg:border-b-0 lg:last:border-r-0"><p className="text-3xl font-black tracking-tight text-blue-950">{stat.value}</p><p className="mt-1 text-xs font-bold uppercase tracking-wider text-slate-500">{stat.label}</p></div>)}</div></section>
    <section className="mx-auto max-w-7xl px-5 py-20 md:py-28 lg:px-8"><div className="grid gap-12 lg:grid-cols-[1.05fr_.95fr] lg:items-center"><div><p className="text-xs font-black uppercase tracking-[0.25em] text-amber-600">{homepage.educationEyebrow}</p><h2 className="mt-5 max-w-3xl text-4xl font-black leading-tight tracking-tight text-blue-950 sm:text-5xl">{homepage.educationTitle}</h2><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-600">{homepage.educationText}</p><div className="mt-8 flex flex-wrap gap-3"><Link to="/academics" className="rounded-xl bg-blue-950 px-6 py-3.5 font-black text-white shadow-lg hover:bg-blue-900">Explore academics</Link><Link to="/about" className="rounded-xl border border-slate-300 px-6 py-3.5 font-black text-slate-700 hover:bg-slate-50">Discover {school.shortName}</Link></div></div><div className="rounded-[2rem] border border-slate-200 bg-slate-50 p-7 shadow-sm md:p-9"><p className="text-xs font-black uppercase tracking-[0.2em] text-amber-600">Our promise</p><div className="mt-7 space-y-7">{homepage.pillars.map((item, i) => <div key={`${item.title}-${i}`} className="flex gap-4"><span className="mt-1 flex h-9 w-9 shrink-0 items-center justify-center rounded-full bg-amber-100 text-xs font-black text-amber-700">{item.number}</span><div><h3 className="text-lg font-black text-blue-950">{item.title}</h3><p className="mt-1 text-sm leading-6 text-slate-600">{item.text}</p></div></div>)}</div></div></div></section>
    <section className="bg-slate-50 py-20 md:py-24"><div className="mx-auto max-w-7xl px-5 lg:px-8"><div className="max-w-3xl"><p className="text-xs font-black uppercase tracking-[0.22em] text-amber-600">{homepage.communityEyebrow}</p><h2 className="mt-3 text-3xl font-black tracking-tight text-blue-950 md:text-4xl">{homepage.communityTitle}</h2><p className="mt-4 text-lg leading-7 text-slate-600">{homepage.communityText}</p></div><div className="mt-10 grid gap-5 md:grid-cols-3">{homepage.pathways.map((item, i) => <Link key={`${item.title}-${i}`} to={item.href} className="group flex flex-col rounded-3xl border border-slate-200 bg-white p-7 shadow-sm transition hover:-translate-y-1 hover:border-blue-200 hover:shadow-xl"><p className="text-xs font-black uppercase tracking-widest text-amber-600">{item.eyebrow}</p><h3 className="mt-3 text-2xl font-black text-blue-950">{item.title}</h3><p className="mt-3 flex-1 leading-7 text-slate-600">{item.text}</p><span className="mt-7 text-sm font-black text-blue-700 group-hover:text-amber-600">{item.action} →</span></Link>)}</div></div></section>
    <LatestNews />
    <section className="mx-auto max-w-7xl px-5 py-20 md:py-24 lg:px-8"><div className="overflow-hidden rounded-[2rem] bg-blue-950 text-white shadow-xl"><div className="grid lg:grid-cols-[1.15fr_.85fr]"><div className="p-8 sm:p-12"><p className="text-xs font-black uppercase tracking-[0.22em] text-amber-300">{homepage.developmentEyebrow}</p><h2 className="mt-3 text-3xl font-black tracking-tight sm:text-4xl">{homepage.developmentTitle}</h2><p className="mt-5 max-w-2xl leading-7 text-blue-100">{homepage.developmentText}</p><div className="mt-7 rounded-2xl border border-white/10 bg-white/5 p-5"><div className="flex items-end justify-between gap-4"><span className="text-sm font-bold text-blue-100">Current campaign</span><span className="text-sm font-black text-amber-300">{homepage.developmentGoal} goal</span></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-white/10"><div className="h-full w-0 rounded-full bg-amber-400" /></div><p className="mt-2 text-xs text-blue-200">Every contribution moves the mission forward.</p></div><Link to="/support" className="mt-8 inline-flex rounded-xl bg-amber-400 px-6 py-3.5 font-black text-blue-950 hover:bg-amber-300">Support our mission</Link></div><div className="relative min-h-[300px] overflow-hidden"><img src="/images/secondary.jpg" alt={`${school.name} community`} className="absolute inset-0 h-full w-full object-cover" /><div className="absolute inset-0 bg-gradient-to-r from-blue-950 via-blue-950/35 to-transparent" /></div></div></div></section>
    <section className="border-t border-slate-100 bg-white py-16"><div className="mx-auto flex max-w-7xl flex-col gap-6 px-5 text-center lg:flex-row lg:items-center lg:justify-between lg:px-8 lg:text-left"><div><p className="text-xs font-black uppercase tracking-[0.2em] text-amber-600">{homepage.finalEyebrow}</p><h2 className="mt-2 text-3xl font-black tracking-tight text-blue-950">{homepage.finalTitle}</h2></div><div className="flex flex-col gap-3 sm:flex-row"><Link to="/contact" className="rounded-xl border border-slate-300 px-6 py-3 font-black text-slate-700 hover:bg-slate-50">Contact us</Link><Link to="/register?role=parent" className="rounded-xl bg-blue-950 px-6 py-3 font-black text-white hover:bg-blue-900">Start an enquiry</Link></div></div></section>
  </main>;
}
