import { useEffect, useMemo, useState } from "react";
import PortalShell from "../components/PortalShell";
import { apiRequest } from "../services/api";

const money = (value) => `KES ${Number(value || 0).toLocaleString()}`;
const csvEscape = (value) => `"${String(value ?? "").replaceAll('"', '""')}"`;

export default function SchoolReports() {
  const [data, setData] = useState(null); const [error, setError] = useState(""); const [loading, setLoading] = useState(true);
  const load = async () => { setLoading(true); setError(""); try { setData(await apiRequest("/reports/school")); } catch (e) { setError(e.message || "Unable to load school reports."); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);
  const rows = useMemo(() => (data?.results || []).map((r) => [r.pupil?.name, r.exam?.name, r.subject?.name, r.marks, r.maxMarks, r.grade || ""]), [data]);
  const exportCsv = () => { if (!rows.length) return; const content = [["Pupil", "Examination", "Subject", "Marks", "Max Marks", "Grade"], ...rows].map((r) => r.map(csvEscape).join(",")).join("\n"); const blob = new Blob([content], { type: "text/csv;charset=utf-8" }); const url = URL.createObjectURL(blob); const a = document.createElement("a"); a.href = url; a.download = `angels-home-results-${new Date().toISOString().slice(0, 10)}.csv`; a.click(); URL.revokeObjectURL(url); };
  if (loading) return <PortalShell role="admin"><div className="rounded-2xl border bg-white p-10 text-center text-slate-500">Loading reporting centre…</div></PortalShell>;
  if (error) return <PortalShell role="admin"><div className="rounded-2xl border border-red-200 bg-red-50 p-6 text-red-700"><p className="font-black">Reports unavailable</p><p className="mt-2 text-sm">{error}</p><button onClick={load} className="mt-4 rounded-xl bg-blue-950 px-4 py-2 text-sm font-bold text-white">Try again</button></div></PortalShell>;
  const s = data?.summary || {}; const attendance = s.attendanceToday || {};
  return <PortalShell role="admin"><div className="space-y-6"><header className="flex flex-col gap-4 rounded-3xl bg-gradient-to-br from-blue-950 to-slate-900 p-6 text-white md:flex-row md:items-end md:justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-amber-300">Angels Home reporting</p><h1 className="mt-2 text-3xl font-black">School Reports & Analytics</h1><p className="mt-2 max-w-2xl text-sm text-blue-100">A live operational view of pupils, attendance, academic results, finance, inventory and upcoming events.</p></div><div className="flex gap-2"><button onClick={load} className="rounded-xl border border-white/20 px-4 py-2.5 text-sm font-bold">Refresh</button><button onClick={() => window.print()} className="rounded-xl bg-amber-400 px-4 py-2.5 text-sm font-black text-blue-950">Print</button></div></header>
  <section className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[["Pupils",s.pupils], ["Teachers",s.teachers], ["Parents",s.parents], ["Sponsors",s.sponsors], ["Classes",s.classes], ["Subjects",s.subjects], ["Open exams",s.openExams], ["Low stock",s.lowStockCount]].map(([label,value]) => <div key={label} className="rounded-2xl border bg-white p-5 shadow-sm"><p className="text-sm font-semibold text-slate-500">{label}</p><p className="mt-2 text-3xl font-black text-blue-950">{value || 0}</p></div>)}</section>
  <section className="grid gap-6 lg:grid-cols-2"><div className="rounded-2xl border bg-white p-6 shadow-sm"><p className="text-xs font-bold uppercase tracking-widest text-amber-600">Today</p><h2 className="mt-1 text-xl font-black text-blue-950">Attendance</h2><div className="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-4">{[["Present",attendance.present],["Absent",attendance.absent],["Sick",attendance.sick],["Late",attendance.late]].map(([label,value]) => <div key={label} className="rounded-xl bg-slate-50 p-4"><p className="text-xs text-slate-500">{label}</p><p className="mt-1 text-2xl font-black text-blue-950">{value || 0}</p></div>)}</div><p className="mt-4 text-sm font-bold text-slate-600">Attendance rate: {s.attendanceRate == null ? "—" : `${s.attendanceRate}%`}</p></div><div className="rounded-2xl border bg-white p-6 shadow-sm"><p className="text-xs font-bold uppercase tracking-widest text-amber-600">This month</p><h2 className="mt-1 text-xl font-black text-blue-950">Academic & finance performance</h2><div className="mt-5 grid grid-cols-2 gap-3"><div className="rounded-xl bg-blue-50 p-4"><p className="text-xs text-blue-600">Results entered</p><p className="mt-1 text-2xl font-black text-blue-950">{s.monthlyResults || 0}</p></div><div className="rounded-xl bg-blue-50 p-4"><p className="text-xs text-blue-600">Average</p><p className="mt-1 text-2xl font-black text-blue-950">{s.monthlyAverage == null ? "—" : `${s.monthlyAverage}%`}</p></div><div className="rounded-xl bg-amber-50 p-4"><p className="text-xs text-amber-700">Collected</p><p className="mt-1 text-2xl font-black text-blue-950">{money(s.monthlyCollected)}</p></div><div className="rounded-xl bg-amber-50 p-4"><p className="text-xs text-amber-700">Payments</p><p className="mt-1 text-2xl font-black text-blue-950">{s.monthlyPayments || 0}</p></div></div></div></section>
  <section className="rounded-2xl border bg-white p-6 shadow-sm print:shadow-none"><div className="flex flex-col gap-3 md:flex-row md:items-center md:justify-between"><div><h2 className="text-xl font-black text-blue-950">Recent examination activity</h2><p className="mt-1 text-sm text-slate-500">Results entered during the current month.</p></div><button onClick={exportCsv} disabled={!rows.length} className="rounded-xl bg-blue-950 px-4 py-2.5 text-sm font-bold text-white disabled:opacity-40">Export CSV</button></div><div className="mt-5 overflow-x-auto"><table className="min-w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="p-3">Pupil</th><th className="p-3">Exam</th><th className="p-3">Subject</th><th className="p-3">Marks</th><th className="p-3">Grade</th></tr></thead><tbody>{data.results?.length ? data.results.map((r) => <tr key={r._id} className="border-t"><td className="p-3 font-bold">{r.pupil?.name || "—"}</td><td className="p-3">{r.exam?.name || "—"}</td><td className="p-3">{r.subject?.name || "—"}</td><td className="p-3">{r.marks}/{r.maxMarks}</td><td className="p-3 font-black text-blue-950">{r.grade || "—"}</td></tr>) : <tr><td colSpan="5" className="p-8 text-center text-slate-500">No results entered this month.</td></tr>}</tbody></table></div></section>
  <section className="grid gap-6 lg:grid-cols-3"><div className="rounded-2xl border bg-white p-6 shadow-sm lg:col-span-2"><h2 className="text-xl font-black text-blue-950">Low-stock alerts</h2><div className="mt-4 space-y-3">{data.lowStock?.length ? data.lowStock.map((item) => <div key={item._id} className="flex items-center justify-between rounded-xl bg-red-50 p-4"><div><p className="font-bold text-slate-900">{item.name}</p><p className="text-xs text-slate-500">Minimum {item.minimumStock} {item.unit}</p></div><p className="font-black text-red-700">{item.quantity} {item.unit}</p></div>) : <p className="rounded-xl bg-emerald-50 p-4 text-sm font-semibold text-emerald-700">No low-stock items.</p>}</div></div><div className="rounded-2xl border bg-white p-6 shadow-sm"><h2 className="text-xl font-black text-blue-950">Upcoming events</h2><div className="mt-4 space-y-3">{data.events?.length ? data.events.slice(0, 6).map((event) => <div key={event._id} className="rounded-xl bg-slate-50 p-4"><p className="font-bold">{event.title}</p><p className="mt-1 text-xs text-slate-500">{new Date(event.startAt).toLocaleString()}</p></div>) : <p className="text-sm text-slate-500">No upcoming events.</p>}</div></div></section></div></PortalShell>;
}
