import { useEffect, useState } from "react";
import PortalShell from "../components/PortalShell";
import { apiRequest } from "../services/api";

const labels = { parent: "Parent", sponsor: "Sponsor" };
const inputClass = "mt-2 w-full rounded-xl border border-slate-300 bg-white px-4 py-3 text-sm outline-none focus:border-blue-600 focus:ring-2 focus:ring-blue-100";

export default function SchoolCoordination() {
  const [data, setData] = useState({ parents: [], sponsors: [], pupils: [] });
  const [form, setForm] = useState({ type: "parent", userId: "", pupilId: "" });
  const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState(""); const [success, setSuccess] = useState("");
  const load = async () => { setError(""); try { const result = await apiRequest("/portal/relationships"); setData({ parents: result.parents || [], sponsors: result.sponsors || [], pupils: result.pupils || [] }); } catch (err) { setError(err.message || "Unable to load relationships."); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  const accounts = form.type === "parent" ? data.parents : data.sponsors;
  const submit = async (event) => { event.preventDefault(); setError(""); setSuccess(""); if (!form.userId || !form.pupilId) return setError("Select both an account and a pupil."); setSaving(true); try { await apiRequest("/portal/relationships", { method: "POST", body: JSON.stringify(form) }); setSuccess(`${labels[form.type]} relationship saved successfully.`); setForm({ ...form, userId: "", pupilId: "" }); await load(); } catch (err) { setError(err.message || "Unable to save relationship."); } finally { setSaving(false); } };
  const remove = async (type, userId, pupilId) => { if (!window.confirm("Remove this relationship? The account will no longer see this pupil's portal information.")) return; setError(""); setSuccess(""); try { await apiRequest("/portal/relationships", { method: "DELETE", body: JSON.stringify({ type, userId, pupilId }) }); setSuccess("Relationship removed."); await load(); } catch (err) { setError(err.message || "Unable to remove relationship."); } };
  return <PortalShell role="admin"><div className="mb-7"><p className="text-xs font-bold uppercase tracking-widest text-amber-600">Administration</p><h1 className="mt-1 text-3xl font-black text-blue-950">Family & sponsor coordination</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-600">Securely connect parents and sponsors to the pupils they are authorised to support. These relationships control which learner information appears in their portals.</p></div>{error && <div className="mb-5 rounded-xl border border-red-200 bg-red-50 p-4 text-sm font-semibold text-red-700" role="alert">{error}</div>}{success && <div className="mb-5 rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-sm font-semibold text-emerald-700" role="status">{success}</div>}<div className="grid gap-6 lg:grid-cols-3"><section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><p className="text-xs font-bold uppercase tracking-widest text-amber-600">New connection</p><h2 className="mt-1 text-xl font-black text-blue-950">Link an account</h2><form onSubmit={submit} className="mt-5 space-y-4"><Field label="Relationship"><select value={form.type} onChange={(e) => setForm({ type: e.target.value, userId: "", pupilId: "" })} className={inputClass}><option value="parent">Parent</option><option value="sponsor">Sponsor</option></select></Field><Field label="Account"><select value={form.userId} onChange={(e) => setForm({ ...form, userId: e.target.value })} className={inputClass}><option value="">Select account</option>{accounts.map((account) => <option key={account._id} value={account._id}>{account.name} · {account.email}</option>)}</select></Field><Field label="Pupil"><select value={form.pupilId} onChange={(e) => setForm({ ...form, pupilId: e.target.value })} className={inputClass}><option value="">Select pupil</option>{data.pupils.map((pupil) => <option key={pupil._id} value={pupil._id}>{pupil.name} · {pupil.email}</option>)}</select></Field><button disabled={saving || loading} className="w-full rounded-xl bg-blue-950 px-5 py-3 text-sm font-black text-white hover:bg-blue-900 disabled:opacity-60">{saving ? "Saving relationship…" : "Link account"}</button></form></section><section className="space-y-6 lg:col-span-2"><RelationshipList title="Parent relationships" type="parent" items={data.parents} field="children" onRemove={remove} /><RelationshipList title="Sponsor relationships" type="sponsor" items={data.sponsors} field="sponsoredPupils" onRemove={remove} /></section></div></PortalShell>;
}
function Field({ label, children }) { return <label className="block"><span className="text-sm font-bold text-slate-700">{label}</span>{children}</label>; }
function RelationshipList({ title, type, items, field, onRemove }) { return <section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-center justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-widest text-amber-600">Coordination</p><h2 className="mt-1 text-xl font-black text-blue-950">{title}</h2></div><span className="rounded-full bg-blue-50 px-3 py-1 text-xs font-black text-blue-800">{items.length} accounts</span></div><div className="mt-5 space-y-3">{items.map((item) => <article key={item._id} className="rounded-xl border border-slate-100 bg-slate-50 p-4"><div className="flex flex-col gap-3 md:flex-row md:items-center md:justify-between"><div><h3 className="font-black text-blue-950">{item.name}</h3><p className="text-xs text-slate-500">{item.email}</p></div><div className="flex flex-wrap gap-2">{(item[field] || []).length ? item[field].map((pupil) => <span key={pupil._id} className="inline-flex items-center gap-2 rounded-full bg-white px-3 py-2 text-xs font-bold text-slate-700 ring-1 ring-slate-200">{pupil.name}<button type="button" onClick={() => onRemove(type, item._id, pupil._id)} className="font-black text-red-600" aria-label={`Remove ${pupil.name}`}>×</button></span>) : <span className="text-xs font-semibold text-slate-400">No pupil linked</span>}</div></div></article>)}{!items.length && <div className="rounded-xl border border-dashed border-slate-300 p-8 text-center text-sm text-slate-500">No active {type} accounts.</div>}</div></section>; }
