import { useCallback, useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { apiRequest } from "../services/api";

const cards = [["Pupils","pupils"],["Parents","parents"],["Teachers","teachers"],["Classes","classes"],["Subjects","subjects"],["Open exams","openExams"]];
export default function SMISDashboard() {
  const [data,setData]=useState(null); const [error,setError]=useState(""); const [refreshing,setRefreshing]=useState(false);
  const load=useCallback(async(silent=false)=>{setError("");if(silent)setRefreshing(true);try{setData((await apiRequest("/smis/dashboard"))?.stats||null);}catch(e){setError(e.message||"Unable to load the SMIS dashboard.");}finally{if(silent)setRefreshing(false);}},[]);
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(()=>{void load();},[load]);
  if(!data&&!error)return <div className="min-h-screen bg-slate-50 p-8"><div className="mx-auto max-w-7xl animate-pulse"><div className="h-40 rounded-3xl bg-slate-200"/></div></div>;
  if(error)return <div className="min-h-screen bg-slate-50 p-8"><div className="mx-auto max-w-2xl rounded-3xl border border-red-200 bg-white p-8"><h1 className="text-2xl font-black text-blue-950">SMIS unavailable</h1><p className="mt-3 text-sm text-red-600">{error}</p><button onClick={()=>load()} className="mt-6 rounded-xl bg-blue-950 px-5 py-3 text-sm font-bold text-white">Try again</button></div></div>;
  const attendance=data.attendanceToday||{};
  return <div className="min-h-screen bg-slate-50 p-5 text-slate-900 md:p-8"><div className="mx-auto max-w-7xl"><header className="rounded-3xl bg-gradient-to-br from-blue-950 via-blue-900 to-slate-900 p-6 text-white shadow-xl md:p-8"><div className="flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.22em] text-amber-300">Angels Home SMIS</p><h1 className="mt-2 text-3xl font-black md:text-4xl">School Management</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-blue-100">Manage pupils, classes, subjects, attendance, examinations and results from one operational centre.</p></div><div className="flex gap-3"><button onClick={()=>load(true)} disabled={refreshing} className="rounded-xl border border-white/20 bg-white/10 px-4 py-3 text-sm font-bold">{refreshing?"Refreshing…":"Refresh"}</button><Link to="/admin/dashboard" className="rounded-xl bg-amber-400 px-4 py-3 text-sm font-black text-blue-950">Admin dashboard</Link></div></div></header>
  <section className="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{cards.map(([label,key])=><div key={key} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-sm font-semibold text-slate-500">{label}</p><p className="mt-2 text-3xl font-black text-blue-950">{data[key]||0}</p></div>)}</section>
  <section className="mt-6 grid gap-6 lg:grid-cols-2"><div className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><p className="text-xs font-bold uppercase tracking-widest text-amber-600">Attendance today</p><h2 className="mt-1 text-xl font-black text-blue-950">Daily attendance overview</h2><div className="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-4">{[["Present",attendance.present],["Absent",attendance.absent],["Sick",attendance.sick],["Late",attendance.late]].map(([label,value])=><div key={label} className="rounded-xl bg-slate-50 p-4"><p className="text-xs font-semibold text-slate-500">{label}</p><p className="mt-1 text-2xl font-black text-blue-950">{value||0}</p></div>)}</div><div className="mt-5 rounded-xl bg-blue-50 p-4"><p className="text-xs font-bold uppercase tracking-wider text-blue-700">Attendance rate</p><p className="mt-1 text-3xl font-black text-blue-950">{attendance.attendanceRate==null?"—":`${attendance.attendanceRate}%`}</p></div></div><div className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><p className="text-xs font-bold uppercase tracking-widest text-amber-600">Academic operations</p><h2 className="mt-1 text-xl font-black text-blue-950">Phase 1 controls</h2><div className="mt-5 grid gap-3"><Link to="/admin/smis/operations" className="rounded-xl bg-blue-950 p-4 font-black text-white hover:bg-blue-900">Open SMIS Operations Centre →</Link><div className="grid gap-3 sm:grid-cols-2"><Link to="/portal/admin/pupils" className="rounded-xl border p-4 font-bold text-blue-950 hover:bg-blue-50">Pupil profiles →</Link><Link to="/portal/admin/relationships" className="rounded-xl border p-4 font-bold text-blue-950 hover:bg-blue-50">Family links →</Link></div></div><p className="mt-5 text-sm leading-6 text-slate-500">Manage admissions profiles, classes, subjects, attendance, examinations and results in the operations centre.</p></div></section></div></div>;
}
