import { useEffect, useMemo, useState } from "react";
import { apiRequest } from "../services/api";
import PortalShell from "../components/PortalShell";

const grade = (marks, max = 100) => { const p = max ? (Number(marks) / Number(max)) * 100 : 0; return p >= 80 ? "A" : p >= 70 ? "B" : p >= 60 ? "C" : p >= 50 ? "D" : p >= 40 ? "E" : "F"; };

export default function SMISResults() {
  const [exams,setExams]=useState([]),[pupils,setPupils]=useState([]),[subjects,setSubjects]=useState([]),[results,setResults]=useState([]);
  const [exam,setExam]=useState(""),[pupil,setPupil]=useState(""),[query,setQuery]=useState(""),[marks,setMarks]=useState({}),[maxMarks,setMaxMarks]=useState(100),[comment,setComment]=useState("");
  const [loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState("");
  const load=async()=>{setLoading(true);setError("");try{const [e,p,s,r]=await Promise.all([apiRequest("/smis/exams"),apiRequest("/smis/pupils"),apiRequest("/smis/subjects"),apiRequest("/smis/results")]);setExams(e.exams||[]);setPupils(p.pupils||[]);setSubjects(s.subjects||[]);setResults(r.results||[]);}catch(err){setError(err.message||"Unable to load results workspace.");}finally{setLoading(false);}};
  useEffect(()=>{void load();},[]);
  const selectedResults=useMemo(()=>results.filter(r=>(!exam||r.exam?._id===exam)&&(!pupil||r.pupil?._id===pupil)),[results,exam,pupil]);
  const selectedPupil=pupils.find(p=>p._id===pupil);
  const reportRows=selectedResults;
  const total=reportRows.reduce((a,r)=>a+Number(r.marks||0),0), maxTotal=reportRows.reduce((a,r)=>a+Number(r.maxMarks||100),0), average=maxTotal?Math.round((total/maxTotal)*100):0;
  const filteredPupils=pupils.filter(p=>`${p.name} ${p.email} ${p.profile?.admissionNumber||""}`.toLowerCase().includes(query.toLowerCase()));
  const save=async()=>{if(!exam||!pupil){setError("Select an exam and pupil first.");return;}const entries=subjects.filter(s=>marks[s._id]!==undefined&&marks[s._id]!=="").map(s=>({pupil,subject:s._id,marks:Number(marks[s._id]),maxMarks:Number(maxMarks),teacherComment:comment}));if(!entries.length){setError("Enter at least one subject mark.");return;}setSaving(true);setError("");setNotice("");try{await apiRequest("/smis/results/bulk",{method:"POST",body:{exam,results:entries}});setNotice(`${entries.length} result(s) saved successfully.`);setMarks({});setComment("");await load();}catch(err){setError(err.message||"Unable to save marks.");}finally{setSaving(false);}};
  return <PortalShell role="admin"><div className="mb-6 flex flex-col gap-3 md:flex-row md:items-end md:justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-amber-600">Angels Home SMIS</p><h1 className="mt-2 text-3xl font-black text-blue-950">Marks & report cards</h1><p className="mt-2 text-slate-600">Enter results, calculate grades and produce a printable term report.</p></div><button onClick={()=>load()} className="rounded-xl border bg-white px-4 py-2.5 text-sm font-bold">Refresh</button></div>
    {error&&<div className="mb-4 rounded-xl bg-red-50 p-4 text-sm font-semibold text-red-700">{error}</div>}{notice&&<div className="mb-4 rounded-xl bg-emerald-50 p-4 text-sm font-semibold text-emerald-700">{notice}</div>}
    <div className="grid gap-6 xl:grid-cols-[1.15fr_.85fr]"><section className="rounded-2xl border bg-white p-5 shadow-sm"><h2 className="text-xl font-black text-blue-950">Marks entry</h2><div className="mt-4 grid gap-3 md:grid-cols-2"><select value={exam} onChange={e=>setExam(e.target.value)} className="rounded-xl border p-3"><option value="">Select examination</option>{exams.map(e=><option key={e._id} value={e._id}>{e.name} · {e.term||"Term"}</option>)}</select><select value={pupil} onChange={e=>setPupil(e.target.value)} className="rounded-xl border p-3"><option value="">Select pupil</option>{filteredPupils.map(p=><option key={p._id} value={p._id}>{p.name}{p.profile?.admissionNumber?` · ${p.profile.admissionNumber}`:""}</option>)}</select></div><div className="mt-3"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Filter pupils…" className="w-full rounded-xl border p-3"/></div>{loading?<p className="p-8 text-center text-slate-500">Loading…</p>:<div className="mt-5 overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="p-3">Subject</th><th className="p-3">Marks</th><th className="p-3">Grade</th></tr></thead><tbody>{subjects.map(s=><tr key={s._id} className="border-t"><td className="p-3 font-bold">{s.name}<span className="ml-2 text-xs text-slate-400">{s.code||""}</span></td><td className="p-3"><input type="number" min="0" max={maxMarks} value={marks[s._id]??""} onChange={e=>setMarks({...marks,[s._id]:e.target.value})} className="w-28 rounded-lg border p-2" placeholder="0"/></td><td className="p-3 font-black text-blue-900">{marks[s._id]!==undefined&&marks[s._id]!==""?grade(marks[s._id],maxMarks):"—"}</td></tr>)}</tbody></table></div>}<div className="mt-4 grid gap-3 md:grid-cols-2"><input type="number" min="1" value={maxMarks} onChange={e=>setMaxMarks(e.target.value)} className="rounded-xl border p-3" placeholder="Maximum marks"/><input value={comment} onChange={e=>setComment(e.target.value)} className="rounded-xl border p-3" placeholder="Teacher comment (optional)"/></div><button disabled={saving} onClick={save} className="mt-4 rounded-xl bg-blue-950 px-5 py-3 font-black text-white disabled:opacity-60">{saving?"Saving…":"Save marks"}</button></section>
    <section className="rounded-2xl border bg-white p-5 shadow-sm print:shadow-none"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-widest text-amber-600">Report card</p><h2 className="mt-1 text-2xl font-black text-blue-950">{selectedPupil?.name||"Select a pupil"}</h2><p className="mt-1 text-sm text-slate-500">{selectedPupil?.profile?.admissionNumber||""}</p></div><button onClick={()=>window.print()} className="rounded-xl bg-amber-400 px-4 py-2.5 text-sm font-black text-blue-950 print:hidden">Print</button></div>{reportRows.length?<><div className="mt-5 grid grid-cols-3 gap-3"><div className="rounded-xl bg-slate-50 p-3"><p className="text-xs text-slate-500">Subjects</p><p className="text-2xl font-black">{reportRows.length}</p></div><div className="rounded-xl bg-slate-50 p-3"><p className="text-xs text-slate-500">Total</p><p className="text-2xl font-black">{total}</p></div><div className="rounded-xl bg-blue-50 p-3"><p className="text-xs text-blue-600">Average</p><p className="text-2xl font-black text-blue-950">{average}%</p></div></div><table className="mt-5 w-full text-left text-sm"><thead className="border-b text-xs uppercase text-slate-500"><tr><th className="py-3">Subject</th><th>Marks</th><th>Grade</th></tr></thead><tbody>{reportRows.map(r=><tr key={r._id} className="border-b"><td className="py-3 font-bold">{r.subject?.name||"—"}</td><td>{r.marks}/{r.maxMarks}</td><td className="font-black">{r.grade||grade(r.marks,r.maxMarks)}</td></tr>)}</tbody></table><div className="mt-5 rounded-xl bg-slate-50 p-4 text-sm"><span className="font-bold">Performance:</span> {average>=80?"Excellent":average>=60?"Good progress":average>=50?"Satisfactory":"Needs improvement"}</div></>:<div className="mt-8 rounded-xl border border-dashed p-8 text-center text-sm text-slate-500">Select an exam and pupil with entered results to generate the report card.</div>}</section></div></PortalShell>;
}
