import { useEffect, useMemo, useState } from "react";
import { Link } from "react-router-dom";
import { apiRequest } from "../services/api";
import PortalShell from "../components/PortalShell";

const modules=[
  ["Academic Years","academic-years","Academic year calendar and current-year control"],["Lesson Planning","lessons","Teacher lesson plans, objectives and assessments"],["Fees & Billing","fees","Fee structures and collected balances"],["Inventory","inventory","Stock, minimum levels and school assets"],["Transport","transport","Routes, pickup points, vehicles and drivers"],["Meals","meals","Daily breakfast, lunch and snack plans"],["Events","events","School calendar and published events"]
];
const initial={"academic-years":{name:"",startDate:"",endDate:"",isCurrent:false},lessons:{schoolClass:"",subject:"",academicYear:"",term:"",topic:"",lessonDate:"",objectives:"",activities:"",assessment:""},fees:{name:"",term:"",academicYear:"",amount:"",dueDate:"",description:""},inventory:{name:"",category:"",quantity:0,unit:"item",minimumStock:0,location:"",supplier:"",unitCost:0},transport:{name:"",pickupPoints:"",fee:0,departureTime:"",returnTime:""},meals:{date:"",breakfast:"",lunch:"",snack:"",dinner:"",notes:""},events:{title:"",description:"",startAt:"",endAt:"",location:"",audience:"all"}};

export default function SMISOperationsHub(){
 const [active,setActive]=useState("academic-years"),[data,setData]=useState({}),[classes,setClasses]=useState([]),[subjects,setSubjects]=useState([]),[form,setForm]=useState(initial["academic-years"]),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[notice,setNotice]=useState(""),[error,setError]=useState("");
 const load=async()=>{setLoading(true);setError("");try{const [c,s,...rows]=await Promise.all([apiRequest("/smis/classes"),apiRequest("/smis/subjects"),...modules.map(([,key])=>apiRequest(`/smis/operations/${key}`))]);setClasses(c.classes||[]);setSubjects(s.subjects||[]);setData(Object.fromEntries(modules.map(([,key],i)=>[key,rows[i]])));}catch(e){setError(e.message||"Unable to load school operations.");}finally{setLoading(false);}};
 useEffect(()=>{load();},[]); useEffect(()=>{setForm(initial[active]);setNotice("");setError("");},[active]);
 const list=useMemo(()=>{const d=data[active]||{};return d[active==="academic-years"?"academicYears":active==="lessons"?"lessons":active==="fees"?"structures":active==="inventory"?"items":active==="transport"?"routes":active==="meals"?"meals":"events"]||[]},[data,active]);
 const update=(k,v)=>setForm(f=>({...f,[k]:v}));
 const save=async()=>{setSaving(true);setError("");setNotice("");try{const payload={...form};for(const k of ["objectives","activities","resources","pickupPoints"])if(typeof payload[k]==="string")payload[k]=payload[k].split(",").map(x=>x.trim()).filter(Boolean);if(active==="lessons"&&!payload.topic)throw new Error("Topic is required.");await apiRequest(`/smis/operations/${active}`,{method:"POST",body:JSON.stringify(payload)});setNotice("Saved successfully.");setForm(initial[active]);await load();}catch(e){setError(e.message||"Unable to save record.");}finally{setSaving(false);}};
 return <PortalShell role="admin"><div className="space-y-6"><header className="rounded-2xl bg-blue-950 p-6 text-white"><p className="text-xs font-bold uppercase tracking-[.2em] text-amber-300">Angels Home SMIS</p><h1 className="mt-2 text-3xl font-black">School Operations Centre</h1><p className="mt-2 max-w-3xl text-sm text-blue-100">Manage the remaining day-to-day school operations from one workspace.</p><div className="mt-5 flex flex-wrap gap-2"><Link to="/admin/smis" className="rounded-xl border border-white/20 px-4 py-2 text-sm font-bold">SMIS Dashboard</Link><Link to="/admin/smis/finance" className="rounded-xl border border-white/20 px-4 py-2 text-sm font-bold">Finance</Link><Link to="/admin/smis/timetable" className="rounded-xl border border-white/20 px-4 py-2 text-sm font-bold">Timetable</Link></div></header>
 {error&&<div className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm font-semibold text-red-700">{error}</div>}{notice&&<div className="rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-sm font-semibold text-emerald-700">{notice}</div>}
 <div className="grid gap-4 lg:grid-cols-[260px_1fr]"><aside className="rounded-2xl border bg-white p-3 shadow-sm">{modules.map(([label,key,desc])=><button key={key} onClick={()=>setActive(key)} className={`mb-1 w-full rounded-xl p-3 text-left ${active===key?"bg-blue-950 text-white":"hover:bg-slate-50"}`}><p className="font-black">{label}</p><p className={`mt-1 text-xs ${active===key?"text-blue-100":"text-slate-500"}`}>{desc}</p></button>)}</aside>
 <main className="rounded-2xl border bg-white p-5 shadow-sm"><div className="flex items-center justify-between gap-3"><div><h2 className="text-xl font-black text-blue-950">{modules.find(x=>x[1]===active)?.[0]}</h2><p className="text-sm text-slate-500">{loading?"Loading records…":`${list.length} record(s)`}</p></div><button onClick={load} className="rounded-xl border px-4 py-2 text-sm font-bold">Refresh</button></div>
 <div className="mt-5 grid gap-3 md:grid-cols-2 lg:grid-cols-3">{Object.entries(form).filter(([k])=>k!=="isCurrent").map(([k,v])=>k==="schoolClass"?<select key={k} value={v} onChange={e=>update(k,e.target.value)} className="rounded-xl border p-3 text-sm"><option value="">Select class</option>{classes.map(c=><option key={c._id} value={c._id}>{c.name}{c.stream?` / ${c.stream}`:""}</option>)}</select>:k==="subject"?<select key={k} value={v} onChange={e=>update(k,e.target.value)} className="rounded-xl border p-3 text-sm"><option value="">Select subject</option>{subjects.map(s=><option key={s._id} value={s._id}>{s.name}</option>)}</select>:<input key={k} type={k.toLowerCase().includes("date")||k.endsWith("at")?"datetime-local":k.includes("amount")||["amount","quantity","minimumStock","unitCost","fee"].includes(k)?"number":"text"} placeholder={k.replace(/([A-Z])/g," $1")} value={Array.isArray(v)?v.join(", "):v} onChange={e=>update(k,e.target.value)} className="rounded-xl border p-3 text-sm" />)}</div>
 {active==="academic-years"&&<label className="mt-3 flex items-center gap-2 text-sm font-semibold"><input type="checkbox" checked={form.isCurrent} onChange={e=>update("isCurrent",e.target.checked)}/> Set as current academic year</label>}
 <button disabled={saving} onClick={save} className="mt-4 rounded-xl bg-amber-400 px-5 py-3 text-sm font-black text-blue-950 disabled:opacity-60">{saving?"Saving…":"Add / Save"}</button>
 <div className="mt-6 overflow-x-auto"><table className="min-w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="p-3">Record</th><th className="p-3">Details</th><th className="p-3">Status</th></tr></thead><tbody>{list.slice(0,100).map((r,i)=><tr key={r._id||i} className="border-t"><td className="p-3 font-bold">{r.name||r.title||r.topic||r.item?.name||r.schoolClass?.name||r.date&&new Date(r.date).toLocaleDateString()||"Record"}</td><td className="p-3 text-slate-600">{r.subject?.name||r.term||r.category||r.description||r.location||r.lunch||r.amount!=null?`${r.subject?.name||r.category||""}${r.amount!=null?` · KES ${r.amount}`:""}`:"—"}</td><td className="p-3 font-semibold">{r.status||r.isActive===false?"Inactive":"Active"}</td></tr>)}</tbody></table>{!list.length&&!loading&&<div className="p-8 text-center text-sm text-slate-500">No records yet. Use the form above to add the first one.</div>}</div></main></div></div></PortalShell>;
}
