import { useCallback, useEffect, useMemo, useState } from "react";
import { apiRequest } from "../services/api";
import PortalShell from "../components/PortalShell";

const tabs = ["Pupils", "Classes", "Subjects", "Attendance", "Exams", "Results"];
const emptyPupil = { pupil: "", admissionNumber: "", dateOfBirth: "", gender: "", schoolClass: "", medical: { allergies: "", conditions: "", medication: "" }, emergencyContacts: [{ name: "", relationship: "", phone: "" }] };

function Panel({ title, subtitle, children, action }) {
  return <section className="rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex flex-col gap-3 border-b border-slate-100 p-5 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="text-lg font-black text-blue-950">{title}</h2>{subtitle && <p className="mt-1 text-sm text-slate-500">{subtitle}</p>}</div>{action}</div><div className="p-5">{children}</div></section>;
}

function Empty({ text }) { return <div className="rounded-xl border border-dashed border-slate-300 p-8 text-center text-sm text-slate-500">{text}</div>; }

export default function SMISOperations() {
  const [tab, setTab] = useState("Pupils");
  const [data, setData] = useState({ pupils: [], classes: [], subjects: [], attendance: [], exams: [], results: [] });
  const [loading, setLoading] = useState(false); const [error, setError] = useState(""); const [notice, setNotice] = useState("");
  const [query, setQuery] = useState(""); const [pupilForm, setPupilForm] = useState(emptyPupil); const [showPupil, setShowPupil] = useState(false);
  const [classForm, setClassForm] = useState({ name: "", stream: "", academicYear: "", capacity: 40 }); const [subjectForm, setSubjectForm] = useState({ name: "", code: "" });
  const [examForm, setExamForm] = useState({ name: "", type: "CAT", term: "Term 1", academicYear: "", startDate: "", endDate: "" });

  const load = useCallback(async () => {
    setLoading(true); setError("");
    try {
      const endpoint = { Pupils: "/smis/pupils", Classes: "/smis/classes", Subjects: "/smis/subjects", Attendance: "/smis/attendance", Exams: "/smis/exams", Results: "/smis/results" }[tab];
      const r = await apiRequest(endpoint); setData((d) => ({ ...d, pupils: r.pupils || d.pupils, classes: r.classes || d.classes, subjects: r.subjects || d.subjects, attendance: r.records || d.attendance, exams: r.exams || d.exams, results: r.results || d.results }));
    } catch (e) { setError(e.message || "Unable to load records."); } finally { setLoading(false); }
  }, [tab]);
  useEffect(() => { void load(); }, [load]);
  const filteredPupils = useMemo(() => data.pupils.filter((p) => `${p.name} ${p.email} ${p.profile?.admissionNumber || ""}`.toLowerCase().includes(query.toLowerCase())), [data.pupils, query]);
  const save = async (endpoint, body, success) => { setError(""); setNotice(""); try { await apiRequest(endpoint, { method: "POST", body }); setNotice(success); await load(); } catch (e) { setError(e.message || "Save failed."); } };

  const renderPupils = () => <Panel title="Pupil profiles" subtitle="Admission records, class placement and safeguarding information." action={<button onClick={() => setShowPupil((v) => !v)} className="rounded-xl bg-blue-950 px-4 py-2.5 text-sm font-bold text-white">{showPupil ? "Close" : "Add profile"}</button>}>
    {showPupil && <form onSubmit={(e) => { e.preventDefault(); save(`/smis/pupils/${pupilForm.pupil}/profile`, pupilForm, "Pupil profile saved."); }} className="mb-6 grid gap-3 rounded-xl bg-slate-50 p-4 md:grid-cols-3">
      <input required value={pupilForm.pupil} onChange={(e) => setPupilForm({ ...pupilForm, pupil: e.target.value })} placeholder="Pupil user ID" className="rounded-lg border p-3" />
      <input value={pupilForm.admissionNumber} onChange={(e) => setPupilForm({ ...pupilForm, admissionNumber: e.target.value })} placeholder="Admission number" className="rounded-lg border p-3" />
      <input type="date" value={pupilForm.dateOfBirth} onChange={(e) => setPupilForm({ ...pupilForm, dateOfBirth: e.target.value })} className="rounded-lg border p-3" />
      <select value={pupilForm.gender} onChange={(e) => setPupilForm({ ...pupilForm, gender: e.target.value })} className="rounded-lg border p-3"><option value="">Gender</option><option>male</option><option>female</option><option>other</option></select>
      <select value={pupilForm.schoolClass} onChange={(e) => setPupilForm({ ...pupilForm, schoolClass: e.target.value })} className="rounded-lg border p-3"><option value="">Class</option>{data.classes.map((c) => <option key={c._id} value={c._id}>{c.name}{c.stream ? ` · ${c.stream}` : ""}</option>)}</select>
      <button className="rounded-lg bg-amber-400 px-4 py-3 font-black text-blue-950">Save profile</button>
    </form>}
    <div className="mb-4"><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search pupils by name, email or admission number…" className="w-full rounded-xl border border-slate-200 p-3 outline-none focus:border-blue-500" /></div>
    {loading ? <div className="p-8 text-center text-slate-500">Loading pupils…</div> : filteredPupils.length ? <div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="p-3">Pupil</th><th className="p-3">Admission</th><th className="p-3">Class</th><th className="p-3">Email</th><th className="p-3">Status</th></tr></thead><tbody>{filteredPupils.map((p) => <tr key={p._id} className="border-t"><td className="p-3 font-bold text-blue-950">{p.name}</td><td className="p-3">{p.profile?.admissionNumber || "—"}</td><td className="p-3">{p.profile?.schoolClass ? `${p.profile.schoolClass.name}${p.profile.schoolClass.stream ? ` · ${p.profile.schoolClass.stream}` : ""}` : "Unassigned"}</td><td className="p-3 text-slate-500">{p.email || "—"}</td><td className="p-3"><span className="rounded-full bg-emerald-50 px-2 py-1 text-xs font-bold text-emerald-700">Active</span></td></tr>)}</tbody></table></div> : <Empty text="No pupil records found." />}
  </Panel>;

  const renderClasses = () => <Panel title="Classes & streams" subtitle="Organise cohorts, academic years and capacity."><form onSubmit={(e) => { e.preventDefault(); save("/smis/classes", classForm, "Class created."); }} className="mb-6 grid gap-3 md:grid-cols-4"><input required placeholder="Class name" value={classForm.name} onChange={(e) => setClassForm({ ...classForm, name: e.target.value })} className="rounded-lg border p-3" /><input placeholder="Stream" value={classForm.stream} onChange={(e) => setClassForm({ ...classForm, stream: e.target.value })} className="rounded-lg border p-3" /><input placeholder="Academic year" value={classForm.academicYear} onChange={(e) => setClassForm({ ...classForm, academicYear: e.target.value })} className="rounded-lg border p-3" /><button className="rounded-lg bg-blue-950 px-4 py-3 font-bold text-white">Create class</button></form>{data.classes.length ? <div className="grid gap-3 md:grid-cols-2 lg:grid-cols-3">{data.classes.map((c) => <article key={c._id} className="rounded-xl border p-4"><h3 className="font-black text-blue-950">{c.name}{c.stream ? ` · ${c.stream}` : ""}</h3><p className="mt-1 text-sm text-slate-500">Academic year: {c.academicYear || "—"}</p><p className="mt-1 text-sm text-slate-500">Capacity: {c.capacity || "—"}</p><p className="mt-3 text-xs font-bold text-emerald-700">{c.classTeacher?.name ? `Teacher: ${c.classTeacher.name}` : "No class teacher assigned"}</p></article>)}</div> : <Empty text="No classes have been configured." />}</Panel>;
  const renderSubjects = () => <Panel title="Subject catalogue" subtitle="Maintain the school subject list and teaching assignments."><form onSubmit={(e) => { e.preventDefault(); save("/smis/subjects", subjectForm, "Subject created."); }} className="mb-6 grid gap-3 md:grid-cols-3"><input required placeholder="Subject name" value={subjectForm.name} onChange={(e) => setSubjectForm({ ...subjectForm, name: e.target.value })} className="rounded-lg border p-3" /><input placeholder="Code" value={subjectForm.code} onChange={(e) => setSubjectForm({ ...subjectForm, code: e.target.value })} className="rounded-lg border p-3" /><button className="rounded-lg bg-blue-950 px-4 py-3 font-bold text-white">Create subject</button></form>{data.subjects.length ? <div className="grid gap-3 md:grid-cols-2 lg:grid-cols-3">{data.subjects.map((s) => <article key={s._id} className="rounded-xl border p-4"><div className="flex items-start justify-between gap-3"><h3 className="font-black text-blue-950">{s.name}</h3><span className="rounded bg-slate-100 px-2 py-1 text-xs font-bold">{s.code || "—"}</span></div><p className="mt-3 text-sm text-slate-500">Teachers assigned: {s.teachers?.length || 0}</p></article>)}</div> : <Empty text="No subjects have been configured." />}</Panel>;
  const renderAttendance = () => <Panel title="Attendance register" subtitle="Review daily attendance recorded by administrators and teachers.">{data.attendance.length ? <div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="p-3">Date</th><th className="p-3">Pupil</th><th className="p-3">Class</th><th className="p-3">Status</th><th className="p-3">Note</th></tr></thead><tbody>{data.attendance.map((r) => <tr key={r._id} className="border-t"><td className="p-3">{new Date(r.date).toLocaleDateString()}</td><td className="p-3 font-bold">{r.pupil?.name || "—"}</td><td className="p-3">{r.schoolClass?.name || "—"}</td><td className="p-3 font-bold capitalize">{r.status}</td><td className="p-3 text-slate-500">{r.note || "—"}</td></tr>)}</tbody></table></div> : <Empty text="No attendance records found." />}</Panel>;
  const renderExams = () => <Panel title="Examination management" subtitle="Create and monitor CATs, midterms, end-term and mock examinations."><form onSubmit={(e) => { e.preventDefault(); save("/smis/exams", examForm, "Exam created."); }} className="mb-6 grid gap-3 md:grid-cols-3"><input required placeholder="Exam name" value={examForm.name} onChange={(e) => setExamForm({ ...examForm, name: e.target.value })} className="rounded-lg border p-3" /><select value={examForm.type} onChange={(e) => setExamForm({ ...examForm, type: e.target.value })} className="rounded-lg border p-3"><option>CAT</option><option>Midterm</option><option>End Term</option><option>Mock</option><option>National Exam Preparation</option></select><input placeholder="Academic year" value={examForm.academicYear} onChange={(e) => setExamForm({ ...examForm, academicYear: e.target.value })} className="rounded-lg border p-3" /><input placeholder="Term" value={examForm.term} onChange={(e) => setExamForm({ ...examForm, term: e.target.value })} className="rounded-lg border p-3" /><input type="date" value={examForm.startDate} onChange={(e) => setExamForm({ ...examForm, startDate: e.target.value })} className="rounded-lg border p-3" /><button className="rounded-lg bg-blue-950 px-4 py-3 font-bold text-white">Create exam</button></form>{data.exams.length ? <div className="grid gap-3 md:grid-cols-2">{data.exams.map((e) => <article key={e._id} className="rounded-xl border p-4"><div className="flex justify-between gap-3"><h3 className="font-black text-blue-950">{e.name}</h3><span className="rounded-full bg-amber-50 px-2 py-1 text-xs font-bold text-amber-700">{e.status}</span></div><p className="mt-2 text-sm text-slate-500">{e.type} · {e.term || "Term"} · {e.academicYear || ""}</p></article>)}</div> : <Empty text="No examinations have been created." />}</Panel>;
  const renderResults = () => <Panel title="Results overview" subtitle="Review marks and automatically calculated grades entered by teachers.">{data.results.length ? <div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="p-3">Pupil</th><th className="p-3">Exam</th><th className="p-3">Subject</th><th className="p-3">Marks</th><th className="p-3">Grade</th></tr></thead><tbody>{data.results.map((r) => <tr key={r._id} className="border-t"><td className="p-3 font-bold">{r.pupil?.name || "—"}</td><td className="p-3">{r.exam?.name || "—"}</td><td className="p-3">{r.subject?.name || "—"}</td><td className="p-3">{r.marks}/{r.maxMarks}</td><td className="p-3"><span className="rounded-full bg-blue-50 px-3 py-1 font-black text-blue-800">{r.grade || "—"}</span></td></tr>)}</tbody></table></div> : <Empty text="No examination results have been entered." />}</Panel>;
  return <PortalShell role="admin"><div className="mb-6"><p className="text-xs font-bold uppercase tracking-[0.2em] text-amber-600">Angels Home SMIS</p><div className="mt-2 flex flex-col gap-3 md:flex-row md:items-end md:justify-between"><div><h1 className="text-3xl font-black text-blue-950">School operations</h1><p className="mt-2 text-slate-600">Run core academic administration from one workspace.</p></div><button onClick={() => load()} disabled={loading} className="rounded-xl border bg-white px-4 py-2.5 text-sm font-bold text-blue-950">{loading ? "Refreshing…" : "Refresh records"}</button></div></div>
    {error && <div className="mb-4 rounded-xl bg-red-50 p-4 text-sm font-semibold text-red-700">{error}</div>}{notice && <div className="mb-4 rounded-xl bg-emerald-50 p-4 text-sm font-semibold text-emerald-700">{notice}</div>}
    <div className="mb-5 flex gap-2 overflow-x-auto rounded-2xl border border-slate-200 bg-white p-2 shadow-sm">{tabs.map((t) => <button key={t} onClick={() => { setTab(t); setNotice(""); setQuery(""); }} className={`whitespace-nowrap rounded-xl px-4 py-2.5 text-sm font-bold ${tab === t ? "bg-blue-950 text-white" : "text-slate-600 hover:bg-slate-50"}`}>{t}</button>)}</div>
    {tab === "Pupils" && renderPupils()}{tab === "Classes" && renderClasses()}{tab === "Subjects" && renderSubjects()}{tab === "Attendance" && renderAttendance()}{tab === "Exams" && renderExams()}{tab === "Results" && renderResults()}
  </PortalShell>;
}
