import DonationForm from "../components/DonationForm";
import TransparencyTracker from "../components/TransparencyTracker";
import { useSchoolSettings } from "../context/SchoolSettingsContext";

export default function Support() {
  const { settings } = useSchoolSettings();
  const { school, support } = settings;
  return <main className="bg-white"><section className="bg-blue-950 px-5 py-20 text-white md:py-28"><div className="mx-auto max-w-7xl"><p className="text-xs font-black uppercase tracking-[0.25em] text-amber-400">Give · partner · build</p><h1 className="mt-5 max-w-4xl text-4xl font-black leading-tight tracking-tight md:text-6xl">{support.title}</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-blue-100">{support.intro}</p></div></section>
<section className="mx-auto max-w-7xl px-5 py-20 md:py-24"><div className="max-w-3xl"><p className="text-xs font-black uppercase tracking-[0.22em] text-amber-600">Priority areas</p><h2 className="mt-3 text-3xl font-black text-blue-950 md:text-4xl">{support.priorityTitle}</h2><p className="mt-4 leading-7 text-slate-600">Choose an area that matters to you or contact {school.shortName} to discuss a partnership tailored to your organisation.</p></div><div className="mt-10 grid gap-6 md:grid-cols-3">{support.priorities.map((item, i) => <div key={`${item.title}-${i}`} className="rounded-3xl border border-slate-200 bg-white p-7 shadow-sm"><div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-amber-50 text-2xl">{item.icon}</div><h3 className="mt-6 text-xl font-black text-blue-950">{item.title}</h3><p className="mt-3 leading-7 text-slate-600">{item.description}</p><p className="mt-5 text-sm font-black text-blue-800">Target · {item.amount}</p></div>)}</div></section>
<section className="bg-slate-50 px-5 py-20"><div className="mx-auto max-w-6xl"><div className="mx-auto max-w-2xl text-center"><p className="text-xs font-black uppercase tracking-widest text-amber-600">Secure giving</p><h2 className="mt-3 text-3xl font-black text-blue-950">Make a contribution</h2><p className="mt-3 leading-7 text-slate-600">{support.donationText}</p></div><div className="mx-auto mt-10 max-w-xl rounded-3xl bg-white p-6 shadow-sm ring-1 ring-slate-200 md:p-8"><DonationForm /></div></div></section>
<section className="mx-auto max-w-6xl px-5 py-20"><TransparencyTracker /></section><section className="bg-blue-50 px-5 py-16"><div className="mx-auto max-w-5xl text-center"><h2 className="text-3xl font-black text-blue-950">Interested in a larger partnership?</h2><p className="mx-auto mt-3 max-w-2xl leading-7 text-slate-600">We welcome organisations, foundations and individuals who want to invest in sustainable education and learner welfare.</p><a href="/contact" className="mt-6 inline-flex rounded-xl bg-blue-950 px-6 py-3.5 font-black text-white">Start a conversation</a></div></section></main>;
}
