const express=require("express");const crypto=require("crypto");
const User=require("../models/User");const PupilProfile=require("../models/PupilProfile");const Exam=require("../models/Exam");const ExamResult=require("../models/ExamResult");const ReportCard=require("../models/ReportCard");const Attendance=require("../models/Attendance");const TeacherProfile=require("../models/TeacherProfile");const {requireSchoolAuth}=require("../middleware/schoolAuth");
const router=express.Router();
const level=(marks)=>{if(marks==null)return{code:"MISSED",label:"Missed Assessment",points:null};const n=Number(marks);if(n>=90)return{code:"EE1",label:"Exceeding Expectation 1",points:8};if(n>=75)return{code:"EE2",label:"Exceeding Expectation 2",points:7};if(n>=58)return{code:"ME1",label:"Meeting Expectation 1",points:6};if(n>=41)return{code:"ME2",label:"Meeting Expectation 2",points:5};if(n>=31)return{code:"AE1",label:"Approaching Expectation 1",points:4};if(n>=21)return{code:"AE2",label:"Approaching Expectation 2",points:3};if(n>=11)return{code:"BE1",label:"Below Expectation 1",points:2};return{code:"BE2",label:"Below Expectation 2",points:1};};
async function build(pupilId,examId){const pupil=await User.findOne({_id:pupilId,role:"pupil",isActive:true}).select("name email classId parentPhone").lean();const profile=await PupilProfile.findOne({pupil:pupilId}).populate("schoolClass","name stream academicYear classTeacher").lean();const exam=await Exam.findById(examId).lean();if(!pupil||!exam)return null;const results=await ExamResult.find({pupil:pupilId,exam:examId}).populate("subject","name code").sort({"subject.name":1}).lean();if(!results.length)return null;const rows=results.map(r=>({...r,achievement:level(r.marks),remark:r.marks==null?"No score recorded.":level(r.marks).label}));const total=rows.reduce((a,r)=>a+(Number(r.marks)||0),0),max=rows.reduce((a,r)=>a+(Number(r.maxMarks)||100),0);const contentHash=crypto.createHash("sha256").update(JSON.stringify({pupil:pupilId,exam:examId,results:rows.map(r=>[r.subject?._id,r.marks,r.maxMarks,r.grade])})).digest("hex");const card=await ReportCard.findOne({pupil:pupilId,exam:examId}).lean();const attendance=await Attendance.aggregate([{$match:{pupil:pupilId}},{$group:{_id:"$status",count:{$sum:1}}}]);let teacherSignatureUrl="";if(profile?.schoolClass?.classTeacher){const tp=await TeacherProfile.findOne({teacher:profile.schoolClass.classTeacher}).lean();teacherSignatureUrl=tp?.signatureUrl||"";}const admin=await User.findOne({role:"admin",isActive:true}).select("signatureUrl").lean();return{pupil,profile,exam,results:rows,attendance:Object.fromEntries(attendance.map(x=>[x._id,x.count])),summary:{total,max,average:max?Math.round(total/max*1000)/10:null,points:rows.reduce((a,r)=>a+(r.achievement.points||0),0)},contentHash,signatures:{...(card||{}),teacherSignatureUrl,institutionSignatureUrl:admin?.signatureUrl||""}};}
async function canAccess(user,pupilId){
 if(user.role==="admin")return true;
 if(user.role==="pupil")return String(user._id)===String(pupilId);
 if(user.role==="parent")return Array.isArray(user.children)&&user.children.some(x=>String(x)===String(pupilId));
 if(user.role==="sponsor")return Array.isArray(user.sponsoredPupils)&&user.sponsoredPupils.some(x=>String(x)===String(pupilId));
 if(user.role==="teacher"){
   const profile=await PupilProfile.findOne({pupil:pupilId}).populate("schoolClass","classTeacher").lean();
   return String(profile?.schoolClass?.classTeacher||"")===String(user._id);
 }
 return false;
}
router.get("/:pupilId/:examId",requireSchoolAuth,async(req,res,next)=>{try{const r=await build(req.params.pupilId,req.params.examId);if(!r)return res.status(404).json({success:false,message:"Report card is not available yet."});if(!(await canAccess(req.schoolUser,req.params.pupilId)))return res.status(403).json({success:false,message:"You do not have access to this report card."});res.json({success:true,report:r});}catch(e){next(e)}});
router.post("/:pupilId/:examId/sign",requireSchoolAuth,async(req,res,next)=>{try{const r=await build(req.params.pupilId,req.params.examId);if(!r)return res.status(404).json({success:false,message:"Report card not found."});if(req.schoolUser.role!=="parent"||!(await canAccess(req.schoolUser,req.params.pupilId)))return res.status(403).json({success:false,message:"Only the linked parent can sign this report card."});const url=String(req.body?.signatureUrl||"").trim();if(!/^https:\/\//i.test(url)||url.length>2000)return res.status(400).json({success:false,message:"Provide a secure hosted signature image URL."});const card=await ReportCard.findOneAndUpdate({pupil:req.params.pupilId,exam:req.params.examId},{pupil:req.params.pupilId,exam:req.params.examId,contentHash:r.contentHash,parentSignatureUrl:url,parentSignedBy:req.schoolUser._id,parentSignedAt:new Date()},{upsert:true,new:true,setDefaultsOnInsert:true});res.json({success:true,reportCard:card});}catch(e){next(e)}});
module.exports=router;