require("dotenv").config();
const express=require("express");const cors=require("cors");const helmet=require("helmet");const morgan=require("morgan");const connectDatabase=require("./config/database");const {limiter,mongoSanitize,xss}=require("./middleware/security");const {startLessonReminderScheduler}=require("./services/lessonReminderScheduler");const mongoose=require("mongoose");const LibraryBook=require("./models/LibraryBook");
const app=express();
const configuredOrigins=(process.env.CLIENT_ORIGINS||"").split(",").map(o=>o.trim().replace(/\/$/,"")).filter(Boolean);
const productionOrigins=["https://angelshome.vercel.app"];
const allowedOrigins=[...new Set([...configuredOrigins,...productionOrigins,...(process.env.NODE_ENV!=="production"?["http://localhost:5173","http://localhost:4173"]:[])])];
const isAllowedOrigin=(origin)=>{
  if(!origin) return true;
  const normalized=String(origin).trim().replace(/\/$/,"");
  if(allowedOrigins.includes(normalized)) return true;
  return /^https:\/\/angelshome(?:-[a-z0-9-]+)?\.vercel\.app$/i.test(normalized);
};
app.set("trust proxy",1);app.disable("x-powered-by");app.use(helmet());app.use(cors({origin(origin,callback){if(isAllowedOrigin(origin))return callback(null,true);return callback(new Error("Origin not allowed by CORS"));},credentials:true,methods:["GET","HEAD","PUT","PATCH","POST","DELETE","OPTIONS"],allowedHeaders:["Content-Type","Authorization"],optionsSuccessStatus:204}));app.use(express.json({limit:process.env.JSON_BODY_LIMIT||"1mb"}));app.use(express.urlencoded({extended:false,limit:process.env.JSON_BODY_LIMIT||"1mb"}));app.use(limiter);app.use(mongoSanitize());app.use(xss());app.use(morgan(process.env.NODE_ENV==="production"?"combined":"dev"));
app.get("/",(req,res)=>res.json({success:true,message:"Angels Home Education Center API running",environment:process.env.NODE_ENV||"development"}));app.get("/health",(req,res)=>res.status(200).json({success:true,status:"healthy"}));app.get("/ready",(req,res)=>{const ready=Boolean(process.env.JWT_SECRET&&(process.env.MONGO_URI||process.env.MONGODB_URI)&&mongooseConnectionReady());return res.status(ready?200:503).json({success:ready,status:ready?"ready":"not_ready"});});
app.use("/api/auth",require("./routes/auth"));app.use("/api/portal",require("./routes/portal"));app.use("/api/dashboard-metrics",require("./routes/dashboardMetrics"));app.use("/api/portal/attendance",require("./routes/portalAttendance"));app.use("/api/learning",require("./routes/learning"));app.use("/api/library",require("./routes/library"));app.use("/api/smis",require("./routes/smis"));app.use("/api/smis/timetable",require("./routes/smisTimetable"));app.use("/api/smis/timetable/resources",require("./routes/smisTimetableResourceAdmin"));app.use("/api/smis/operations",require("./routes/schoolOperations"));app.use("/api/finance",require("./routes/finance"));app.use("/api/reports",require("./routes/reports"));app.use("/api/notifications",require("./routes/notifications"));app.use("/api/whatsapp",require("./routes/whatsapp"));app.use("/api/contact",require("./routes/contact"));app.use("/api/donations",require("./routes/donations"));app.use("/api/mpesa",require("./routes/mpesa"));app.use("/api/paypal",require("./routes/paypal"));app.use("/api/admin",require("./routes/admin"));app.use("/api/cms",require("./routes/cms"));app.use((req,res)=>res.status(404).json({success:false,message:"Route not found"}));app.use((error,req,res,next)=>{if(error?.message==="Origin not allowed by CORS")return res.status(403).json({success:false,message:"Origin not allowed"});console.error("Unhandled server error:",error);return res.status(error?.status||500).json({success:false,message:process.env.NODE_ENV==="production"?"Internal server error":error.message});});
const PORT=Number(process.env.PORT)||5000;const mongooseConnectionReady=()=>mongoose.connection.readyState===1;const initializeLibrary=async()=>{const count=await LibraryBook.countDocuments({isActive:true});if(count>0){console.log(`Library catalogue already contains ${count} active titles.`);return;}const books=[{title:"Mathematics for Primary Schools",author:"School Mathematics Department",category:"Mathematics",subject:"Mathematics",publisher:"Angels Home Education Centre",year:2026,location:"A-01",description:"Core mathematics reference for primary learners.",totalCopies:5},{title:"English Language Skills",author:"School English Department",category:"Languages",subject:"English",publisher:"Angels Home Education Centre",year:2026,location:"A-02",description:"Reading, writing, grammar and communication practice.",totalCopies:5},{title:"Integrated Science",author:"School Science Department",category:"Science",subject:"Science",publisher:"Angels Home Education Centre",year:2026,location:"A-03",description:"Foundational science learning resource.",totalCopies:4},{title:"Social Studies and Citizenship",author:"School Humanities Department",category:"Social Studies",subject:"Social Studies",publisher:"Angels Home Education Centre",year:2026,location:"A-04",description:"Community, citizenship and social studies reference.",totalCopies:4},{title:"Computer Studies",author:"School ICT Department",category:"Technology",subject:"ICT",publisher:"Angels Home Education Centre",year:2026,location:"A-05",description:"Introduction to digital literacy and computer studies.",totalCopies:3}];await LibraryBook.insertMany(books.map(b=>({...b,availableCopies:b.totalCopies,isActive:true})));console.log(`Initialized library catalogue with ${books.length} titles.`);};async function start(){if(!process.env.JWT_SECRET)throw new Error("JWT_SECRET must be configured");if(!(process.env.MONGO_URI||process.env.MONGODB_URI))throw new Error("MONGO_URI/MONGODB_URI must be configured");await connectDatabase();await initializeLibrary();const server=app.listen(PORT,()=>{console.log(`Server running on port ${PORT}`);startLessonReminderScheduler();});const shutdown=signal=>{console.log(`${signal} received; shutting down gracefully.`);server.close(()=>{try{mongoose.connection.close(false).finally(()=>process.exit(0));}catch{process.exit(0);}});};process.once("SIGTERM",()=>shutdown("SIGTERM"));process.once("SIGINT",()=>shutdown("SIGINT"));}if(require.main===module)start().catch(error=>{console.error("Server startup failed:",error.message);process.exit(1);});module.exports=app;
